### PR TITLE
When upgrading from pre-1.0, tree information may not properly update

### PR DESCRIPTION
**Pull request by ddb4github**

### CODE REVIEW

**Review by TheWitness — APPROVED** [review]
This looks good for me.

**Comment by TheWitness** [comment]
Mark, if you could merge before release, I would appreciate it.

**Comment by TheWitness** [comment]
@netniV 👍

**Review by netniV — APPROVED** [review]

**Review by netniV — CHANGES_REQUESTED** [review]
If this is related to an existing issue, is there a CHANGELOG entry already? If not, one should be created.

**Pull request merged**
