### PR TITLE
feature: Error dialog is now prominent to prevent missing details

### PR DESCRIPTION
**Pull request by netniV**
Here is my patch to display the dialog.  Give it a whirl but I think we need to make a CSS change to display the information in larger text now that it's got its own dialog.  The two classes used are still the same textError and textInfo (not sure if they are used elsewhere so I didn't modify them for this patch).

### CODE REVIEW

**Comment by netniV** [comment]
Forgot to mention, information dialog will disappear after three seconds.  An error message will stay until OK is clicked.

**Comment by netniV** [comment]
screen shot 2018-02-18 at 17 05 57
screen shot 2018-02-18 at 17 05 42
screen shot 2018-02-18 at 16 11 39

**Comment by cigamit** [comment]
I removed display_output_messages() from the header, removed display_messages() function, it was a waste.

What I did was to set a base64 encoded message variable in global session, and then move the display_messages() javascript to layout.js.  Much cleaner that it was before.

actionfailed

**Comment by cigamit** [comment]
lastly, I did not change the behavior of successful messages, but I like the idea of timing down the message dialog, we would have to put a do-not-hide button to cancel the timeout though for people who would want to keep the dialog from disappearing.

**Comment by netniV** [comment]
One thing I did see occasionally, more when looking at the plugins page, occasionally I got a problem where $ wasn't defined.  I've not replicated it again since, but that might explain why sometimes the message wasn't seen.

**Comment by cigamit** [comment]
Let me see if I can put a bow on this.

**Comment by cigamit** [comment]
Took the best parts of this to resolve #1366.  The resolution for 1366 makes the message propagation between the browser and the server a easier to comprehend.  It's a mess that has been on my plate to clean up for some time.  Thanks for getting the ball rolling.

**Pull request closed without merging**
