### PR TITLE
RRD optimisations

### PR DESCRIPTION
**Pull request by reboot1983**
- Added missing globals
- Removed unused globals
- Optimised rrdtool_function_create() by moving queries and a function call out of the foreach()
- Optimised rrdtool_cacti_compare() by moving queries and a function call out of the foreach()
- Fixed small bug (== instead of =) in rrdtool_cacti_compare()
- Fixed parameters in html_header() calls. Function accepts only 2 parameters (4 given).
- Optimised rrdtool_function_update()

Also, the following functions are not doing anything and are not used in the Cacti code (maybe reports or plugins?). I'm unsure if they can be removed.
- rrd_check()
- rrd_repair()

### CODE REVIEW

**Comment by cigamit** [comment]
I think you may have missed something, the ifHighSpeed is used to set the max value in the RRDfile during creation, the value of ifHighSpeed can change by index value.  When you pulled that out of the loop did you not unintentionally break the setting of the max value for some data sources?  Much of the rest of it is fine.  Also, leave those functions.  If Reinhard ever get's bored of wood working, I want to make sure we don't loose his work.

**Comment by reboot1983** [comment]
I believe that the outcome of the queries and function call of substitute_snmp_query_data(), that I've moved out of the loop, is every iteration the same. In the loop, there is no writing to the tables that are queried. The only thing I see happening here is that, in the end, the $create_ds variable is being filled with calculated values. This is for rrdtool_function_create() and rrdtool_cacti_compare() the same scenario.

The only time the outcome of substitute_snmp_query_data() can be different is where the first parameter $data_source['rrd_maximum'] is being used. And I haven't moved that call from the loop.

Please correct me if i'm wrong or don't understand the issue.

**Comment by cigamit** [comment]
I'll do a second peer review this weekend.  Likely on Sunday.  Pretty busy at the moment.

**Comment by cigamit** [comment]
Reboot, it looks like we've over optimized.  Graph creation does not work right now when you choose to use an per data source or per graph settings as opposed to the templates.  I'm investigating now, but this is a major problem.  Give it a whirl.  SNMP - Get Processor and Host MIB - Logged in users are good candidates to expose.

**Comment by cigamit** [comment]
I think I found the issue in wc3 optimizations.

**Comment by reboot1983** [comment]
I'm getting in the CLOG when trying to create graphs:

```
2017-05-05 14:24:34 - CMDPHP PHP ERROR NOTICE Backtrace: (/graphs_new.php: 37 form_save)(/graphs_new.php: 114 host_new_graphs_save)(/graphs_new.php: 233 push_out_host)(/lib/utility.php: 590 CactiErrorHandler)(/lib/functions.php: 4295 cacti_debug_backtrace)
2017-05-05 14:24:34 - ERROR PHP NOTICE: Undefined index: snmp_version in file: /var/www/html/cactidev/lib/utility.php on line: 590
2017-05-05 14:24:34 - CMDPHP PHP ERROR NOTICE Backtrace: (/graphs_new.php: 37 form_save)(/graphs_new.php: 114 host_new_graphs_save)(/graphs_new.php: 233 push_out_host)(/lib/utility.php: 590 CactiErrorHandler)(/lib/functions.php: 4295 cacti_debug_backtrace)
2017-05-05 14:24:34 - ERROR PHP NOTICE: Undefined index: snmp_password in file: /var/www/html/cactidev/lib/utility.php on line: 590
2017-05-05 14:24:34 - CMDPHP PHP ERROR NOTICE Backtrace: (/graphs_new.php: 37 form_save)(/graphs_new.php: 114 host_new_graphs_save)(/graphs_new.php: 233 push_out_host)(/lib/utility.php: 590 CactiErrorHandler)(/lib/functions.php: 4295 cacti_debug_backtrace)
2017-05-05 14:24:34 - ERROR PHP NOTICE: Undefined index: snmp_username in file: /var/www/html/cactidev/lib/utility.php on line: 590
2017-05-05 14:24:34 - CMDPHP PHP ERROR NOTICE Backtrace: (/graphs_new.php: 37 form_save)(/graphs_new.php: 114 host_new_graphs_save)(/graphs_new.php: 233 push_out_host)(/lib/utility.php: 590 CactiErrorHandler)(/lib/functions.php: 4295 cacti_debug_backtrace)
2017-05-05 14:24:34 - ERROR PHP NOTICE: Undefined index: snmp_community in file: /var/www/html/cactidev/lib/utility.php on line: 590
2017-05-05 14:24:34 - CMDPHP PHP ERROR NOTICE Backtrace: (/graphs_new.php: 37 form_save)(/graphs_new.php: 114 host_new_graphs_save)(/graphs_new.php: 233 push_out_host)(/lib/utility.php: 590 CactiErrorHandler)(/lib/functions.php: 4295 cacti_debug_backtrace)
2017-05-05 14:24:34 - ERROR PHP NOTICE: Undefined index: hostname in file: /var/www/html/cactidev/lib/utility.php on line: 590

**Pull request merged**
