### PR TITLE
Update OIDs on net-snmp_devio.xml

### PR DESCRIPTION
**Pull request by ChestersGarage**
Graphs based on this XML file were not showing any data.  Did a review of all the OIDs and found the two had the wrong OIDs for IO Bytes read/written, being ...12 and ...13.  Changing them to 3 and 4 fixed the graphs.

### CODE REVIEW

**Comment by TheWitness** [comment]
Those are the 32 bit counters.  How old is your net-snmp?

**Comment by TheWitness** [comment]
So, this one won't make it into mainline, as least not in the current form.

**Comment by ChestersGarage** [comment]
This in on Limetech's unRAID platform, using a SNMP plugin.  I'll have to talk to the SNMP plugin maintainer about that.  Looks like I'm keeping this as a custom file for now.

**Comment by ChestersGarage** [comment]
NET-SNMP version: 5.9, compiled for x86_64.

**Comment by TheWitness** [comment]
Yea, tell them to update their agent to support the 64 bit counters.  That would be great.

**Pull request closed without merging**
