### PR TITLE
fix js error

### PR DESCRIPTION
**Pull request by xmacan**

### CODE REVIEW

**Comment by netniV** [comment]
Any details on this?

You've removed the opening of a function but is that right? Should the closing bracket be inserted instead ?

**Comment by TheWitness** [comment]
Good catch, was generating a JS error.  Can you see if you can correct the logo placement issues on the various theme login pages too?  For example, Modern is way off to the bottom left.

**Comment by xmacan** [comment]
ok, I'll look at the position of the logo

**Comment by xmacan** [comment]
Tested all themes and I don't see any problem. Maybe someone already fixed it

**Pull request merged**
