### PR TITLE
Feature #1588: Check that PHP can run a test file

### PR DESCRIPTION
**Pull request by netniV**
Feature #1588: Check that PHP can run a test file

### CODE REVIEW

**Comment by cigamit** [comment]
Looks good.  I'm assuming it's ready to merge right?

**Comment by netniV** [comment]
Yes.

**Comment by netniV** [comment]
No, adding another feature.

**Comment by cigamit** [comment]
Let me know when you think it's ready.

**Comment by netniV** [comment]
This now includes #1628 Allow the User to define a initial Network Discovery during Setup and is ready to be merged.

**Comment by cigamit** [comment]
Made a few minor edits.

**Pull request merged**
