### PR TITLE
Further changes for #1323 to disable form data until checked

### PR DESCRIPTION
**Pull request by netniV**
This provides extra functionality on top of the changes already made for #1323 to prevent being able to click on form data items until the checkbox is actually checked.  This manages this by using the smallest possible change of adding the ui-state-disabled class to the formData DIV and making a combo class selection of formData+ui-state-disabled prevent any pointer-events from working.

Haven't tested it in all browsers, but works well in Chrome.

### CODE REVIEW

**Comment by cigamit** [comment]
There is a problem here.  When the checkbox is checked, the value on the right becomes a preset.  So, there are many cases where you check the checkbox, but still provide a default value.  With that said, what do you think?  I guess we could keep it disabled, but provide a message that says the current value is the preset, to change the preset value, uncheck, and then change the value.  Comments welcome.

**Comment by netniV** [comment]
Doesn't that depend on where the functionality is used?  For example, on the change device settings, it's the value that WILL be used not just a preset?  Maybe the various forms need a small intro that explains what setting the value means?

**Comment by cigamit** [comment]
I'm going to do this, but just a little bit different.  So, I'll close this one for now.  I now know why you did what you did.  But we have to implement it a little bit differently.

**Comment by netniV** [comment]
Fair enough :) I'll check out the commit when I find it later.

**Pull request closed without merging**
