### PR TITLE
Installer: Check temporary path is writable 

### PR DESCRIPTION
**Pull request by inode64**
If path temporary isn't writeable, It shows two problems:
* The templates aren't installed
* You never can do login

### CODE REVIEW

**Comment by netniV** [comment]
This is a good idea.  The installer has currently undergone a major rewrite so some parts of t his would need to be migrated where others would just slot right in.  So, I think we should keep this open as a reminder but make the changes manual in that pull request #1586

**Comment by cigamit** [comment]
I have one problem with this, the variable is not being used anywhere.  So, why does it exist in the settings array?

**Comment by netniV** [comment]
The variable is used by the installer.  It displays the file paths.

**Comment by netniV** [comment]
I'll make the change in the new installer.

**Comment by cigamit** [comment]
So, I won't merge.  We'll just leave this open until you are ready to close it.

**Comment by netniV** [comment]
Thanks for the update @inode64 but I think I'm going to go a slightly different route and block the installer altogether if the path isn't available.  Most cacti functions are going to rely on various temporary files at some point or other so the directory should be writable.

**Comment by inode64** [comment]
Ok , let's changes to code, and I check it in my installations when you finish

**Comment by inode64** [comment]
Other suggestion:
You verify path /rra is writeable too, only when Cacti is Primary Server

**Comment by netniV** [comment]
I think RRA is one of those covered but i'm going to be looking at this shortly so I'll let you know. 👍

**Comment by netniV** [comment]
I've double checked and the installer isn't checking for the RRA being writable by the website.  Though often the writing entity is the polling user not the apache one.  

We could have even take this a step further to check the poller's user.  Since the poller is often run as another user, we could allow a setting within config.php of poller_user.  This would have allowed us to verify that user also had write access but unfortunately PHP's functions do not extend to specifying a user so we would have to implement OS specific workarounds.

**Comment by netniV** [comment]
One other thing that has come to mind, the RRA's may not even be on the installation server.  The ability to use an RRD proxy means they could be elsewhere.  I'm going to give a little more time and thought to the RRA folder tonight.

**Comment by netniV** [comment]
This pull request has been merged in other commits and so I will now close it.

**Pull request closed without merging**
