### PR TITLE
Add IP address to the login audit for successful logins

### PR DESCRIPTION
**Pull request by xmacan**
Request from the forum. I agree with that. My customers use the log analyzer and the IP address information is missing for successful logins.

If you are agree with that I will prepare the same for 1.3

### CODE REVIEW

**Comment by browniebraun** [comment]
No concerns from my side.

**Review by TheWitness — APPROVED** [review]

**Comment by bmfmancini** [comment]
This is also covered in my recent changes of the audit plugin

**Comment by ddb4github** [comment]
Totally, Cacti 1.3.x have 34 LOGIN logs. 
This issue/PR append IP Address for 8 of 33 logs.
Was other 25 logs deprecated for audit? or non-one care others?

Thanks.

**Comment by xmacan** [comment]
@ddb4github thank you for reporting. It was quick fix, it seems that I overlooked it. I will revise it soon

**Pull request merged**
