### PR TITLE
Add the following hability to the walk method for data_query :

### PR DESCRIPTION
**Pull request by earendilfr**
* VALUE/TEST:(test):(true):(false)
   Check the value with the "test" field and return "true" field if match, "false" field in other cases

* VALUE/TABLE:(value1):(return1):...:(valueX):(returnX)
  Check the value with the "valueX" field and return the corresponding "returnX" field if it's match
  If no "valueX" field match, it return 'N/A'

* VALUE/HEX2IP:(start_nbr):(end_nbr)
  Replace the IP address in hexadecimal mode in numerical format (very usefull for F5 devices)
  The "start_nbr" and "end_nbr" allow to limit the convertion to a part of the value (usefull when the mib return the IP address and the netmask

### CODE REVIEW

**Comment by earendilfr** [comment]
You can found in attachment a ressource file for F5 Virtual Server that use this request
[f5_vs.txt](https://github.com/Cacti/cacti/files/806594/f5_vs.txt)

**Comment by ronytomen** [comment]
Pretty cool!  Care to take a stab at updating the documentation? 

`docs/build/manual.sgml`

**Comment by earendilfr** [comment]
I have add the documentation in sgml.

And I have also add the commit for the #347 ticket

**Comment by cigamit** [comment]
This merge request broke standard data queries.  Issue #378 has many people complaining.  I have revered lib/data_query.php for now.  Please open a new pull request when you have resolved these issues.

**Pull request merged**
