### PR TITLE
fixed typo in select statement

### PR DESCRIPTION
**Pull request by Givo29**

### CODE REVIEW

**Comment by cigamit** [comment]
Thanks for finding this!

**Comment by Givo29** [comment]
No worries

**Comment by netniV** [comment]
Well, more importantly, why is there an EXECUTE for a SELECT statement?

**Comment by netniV** [comment]
Ah, I've seen this DELECT statement before, quite recently actually.  One of our developers decided to merge two different keywords to create his own in commit d0e6ef8ee86911e67f1f26aebcdc74a4394d1e18

In reality, this PR is unfortunately completely wrong, and I have now corrected this in commit 1d4195ca

**Comment by Givo29** [comment]
Huh, sorry. My mistake

**Comment by netniV** [comment]
It was our mistake originally, was a good spot.  Anyone with multiple color codes of the same number would have potentially had upgrade issues.

**Pull request merged**
