### PR TITLE
resolving issue #1567

### PR DESCRIPTION
**Pull request by xmacan**
Technical support - add warning if versions are different

### CODE REVIEW

**Comment by xmacan** [comment]
Sorry, I forgot modify CHANGELOG. I made second commit. Is that right?

**Comment by netniV** [comment]
Did you push the second commit up on the same branch?

**Comment by xmacan** [comment]
Yes, I see  Files changed 2

**Comment by xmacan** [comment]
commit 335bd32036b092fe89cd975dfccaba6b3ae3ec49 (HEAD -> issue-1567, origin/issue-1567)
Author: Petr Macek <petr.macek@kostax.cz>
Date:   Sat Jun 30 01:04:57 2018 +0200

    resolving issue #1567

**Comment by cigamit** [comment]
Looks good thanks!

**Pull request merged**
