### PR TITLE
CLOG Enhancements

### PR DESCRIPTION
**Pull request by reboot1983**
I've implemented some CLOG enhancements. 

-feature: CLOG timestamp is now formatted as defined in settings
-feature: CLOG can show loginformation from rotated logfiles

Also:
- Fixed: added GDC_DOT to global_constants.php and global_arrays.php, and refactored the usage of global $datechar
- Fixed some translation strings in CLOG

### CODE REVIEW

**Comment by reboot1983** [comment]
If you replace the mentioned line with:

```
	$dateCharSetting = read_config_option('default_datechar');
	if (empty($dateCharSetting)) {
		$dateCharSetting = GDC_SLASH;
	}
	$datecharacter = $datechar[$dateCharSetting];
```

Does the error still appear?

**Comment by smiles1969** [comment]
That error is gone, but now I'm seeing segfaults in the log.


[Thu Jun 01 14:48:53.096045 2017] [core:notice] [pid 8821] AH00052: child pid 22840 exit signal Segmentation fault (11)

**Comment by smiles1969** [comment]
This strace output of my current apache process of any use?

root@ctcv-cacti2:/var/www/html/cacti# strace -v -s 256 -p 8821 
Process 8821 attached
select(0, NULL, NULL, NULL, {0, 5531})  = 0 (Timeout)
wait4(-1, 0x7ffe65e8ea2c, WNOHANG|WSTOPPED, NULL) = 0
select(0, NULL, NULL, NULL, {1, 0})     = 0 (Timeout)
wait4(-1, 0x7ffe65e8ea2c, WNOHANG|WSTOPPED, NULL) = 0
select(0, NULL, NULL, NULL, {1, 0})     = 0 (Timeout)
wait4(-1, 0x7ffe65e8ea2c, WNOHANG|WSTOPPED, NULL) = 0
select(0, NULL, NULL, NULL, {1, 0})     = 0 (Timeout)
wait4(-1, 0x7ffe65e8ea2c, WNOHANG|WSTOPPED, NULL) = 0
select(0, NULL, NULL, NULL, {1, 0})     = 0 (Timeout)
wait4(-1, 0x7ffe65e8ea2c, WNOHANG|WSTOPPED, NULL) = 0
select(0, NULL, NULL, NULL, {1, 0})     = 0 (Timeout)
wait4(-1, 0x7ffe65e8ea2c, WNOHANG|WSTOPPED, NULL) = 0
select(0, NULL, NULL, NULL, {1, 0})     = 0 (Timeout)
wait4(-1, 0x7ffe65e8ea2c, WNOHANG|WSTOPPED, NULL) = 0
select(0, NULL, NULL, NULL, {1, 0})     = ? ERESTARTNOHAND (To be restarted if no handler)
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_KILLED, si_pid=26799, si_uid=33, si_status=SIGSEGV, si_utime=34, si_stime=3} ---
select(0, NULL, NULL, NULL, {0, 980317}) = ? ERESTARTNOHAND (To be restarted if no handler)
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_KILLED, si_pid=26800, si_uid=33, si_status=SIGSEGV, si_utime=24, si_stime=5} ---
select(0, NULL, NULL, NULL, {0, 641889}) = ? ERESTARTNOHAND (To be restarted if no handler)
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_KILLED, si_pid=26801, si_uid=33, si_status=SIGSEGV, si_utime=32, si_stime=2} ---
select(0, NULL, NULL, NULL, {0, 243200}) = 0 (Timeout)
clone(child_stack=0, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7f9208efaa50) = 29562
wait4(-1, [{WIFSIGNALED(s) && WTERMSIG(s) == SIGSEGV}], WNOHANG|WSTOPPED, NULL) = 26799
write(2, "[Thu Jun 01 15:24:36.199547 2017] [core:notice] [pid 8821] AH00052: child pid 26799 exit signal Segmentation fault (11)\n", 120) = 120
wait4(-1, [{WIFSIGNALED(s) && WTERMSIG(s) == SIGSEGV}], WNOHANG|WSTOPPED, NULL) = 26800
write(2, "[Thu Jun 01 15:24:36.199835 2017] [core:notice] [pid 8821] AH00052: child pid 26800 exit signal Segmentation fault (11)\n", 120) = 120
wait4(-1, [{WIFSIGNALED(s) && WTERMSIG(s) == SIGSEGV}], WNOHANG|WSTOPPED, NULL) = 26801
write(2, "[Thu Jun 01 15:24:36.199992 2017] [core:notice] [pid 8821] AH00052: child pid 26801 exit signal Segmentation fault (11)\n", 120) = 120
wait4(-1, 0x7ffe65e8ea2c, WNOHANG|WSTOPPED, NULL) = 0
select(0, NULL, NULL, NULL, {1, 0})     = ? ERESTARTNOHAND (To be restarted if no handler)
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_KILLED, si_pid=26802, si_uid=33, si_status=SIGSEGV, si_utime=25, si_stime=3} ---
select(0, NULL, NULL, NULL, {0, 922953}) = ? ERESTARTNOHAND (To be restarted if no handler)
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_KILLED, si_pid=26803, si_uid=33, si_status=SIGSEGV, si_utime=34, si_stime=3} ---
select(0, NULL, NULL, NULL, {0, 498730}) = ? ERESTARTNOHAND (To be restarted if no handler)
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_KILLED, si_pid=26804, si_uid=33, si_status=SIGSEGV, si_utime=34, si_stime=1} ---
select(0, NULL, NULL, NULL, {0, 99941}) = 0 (Timeout)
clone(child_stack=0, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7f9208efaa50) = 29563
clone(child_stack=0, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7f9208efaa50) = 29564
wait4(-1, [{WIFSIGNALED(s) && WTERMSIG(s) == SIGSEGV}], WNOHANG|WSTOPPED, NULL) = 26802
write(2, "[Thu Jun 01 15:24:37.207250 2017] [core:notice] [pid 8821] AH00052: child pid 26802 exit signal Segmentation fault (11)\n", 120) = 120
wait4(-1, [{WIFSIGNALED(s) && WTERMSIG(s) == SIGSEGV}], WNOHANG|WSTOPPED, NULL) = 26803
write(2, "[Thu Jun 01 15:24:37.207430 2017] [core:notice] [pid 8821] AH00052: child pid 26803 exit signal Segmentation fault (11)\n", 120) = 120
wait4(-1, [{WIFSIGNALED(s) && WTERMSIG(s) == SIGSEGV}], WNOHANG|WSTOPPED, NULL) = 26804
write(2, "[Thu Jun 01 15:24:37.207552 2017] [core:notice] [pid 8821] AH00052: child pid 26804 exit signal Segmentation fault (11)\n", 120) = 120
wait4(-1, 0x7ffe65e8ea2c, WNOHANG|WSTOPPED, NULL) = 0
select(0, NULL, NULL, NULL, {1, 0})     = ? ERESTARTNOHAND (To be restarted if no handler)
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_KILLED, si_pid=29562, si_uid=33, si_status=SIGSEGV, si_utime=34, si_stime=2} ---
select(0, NULL, NULL, NULL, {0, 645305}) = 0 (Timeout)
clone(child_stack=0, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7f9208efaa50) = 29565
clone(child_stack=0, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7f9208efaa50) = 29566
clone(child_stack=0, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7f9208efaa50) = 29567
clone(child_stack=0, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7f9208efaa50) = 29568
wait4(-1, [{WIFSIGNALED(s) && WTERMSIG(s) == SIGSEGV}], WNOHANG|WSTOPPED, NULL) = 29562
write(2, "[Thu Jun 01 15:24:38.224008 2017] [core:notice] [pid 8821] AH00052: child pid 29562 exit signal Segmentation fault (11)\n", 120) = 120

**Comment by reboot1983** [comment]
Wut? Cannot compute.. This one makes no sense for me. The issue you had, was that the config setting was empty. So we needed a fallback or else we would get an undefined index of <nothing>.

But the new error you have makes no sense for me at all. This cannot be a Cacti error? Isn't this a Apache thing? https://bz.apache.org/bugzilla/show_bug.cgi?id=56984

**Comment by smiles1969** [comment]
The segfaults may not be even related to this particular commit, but it's related to the commits that have been done since 1.1.7. My apache is running several other sites, just not the cacti site now. 

Your changes have fixed the original issue, and I noted the other affected files as well.

Thanks for your help reboot1983.

**Pull request merged**
