### PR TITLE
fix incorrect variable in ping

### PR DESCRIPTION
**Pull request by xmacan**
sorry for this

### CODE REVIEW

**Comment by xmacan** [comment]
@TheWitness  don't forget merge it to develop too, thank you

**Comment by TheWitness** [comment]
On the road.  I'll get there.  Likely Sunday.  @netniV can also cherry-pick.

**Comment by xmacan** [comment]
@TheWitness You didn't forget this?

**Comment by TheWitness** [comment]
You mean to move into `develop`?

**Comment by xmacan** [comment]
yes

**Comment by TheWitness** [comment]
Leave that for Sunday.

**Pull request merged**
