### PR TITLE
French translation correction

### PR DESCRIPTION
**Pull request by mikygee**
Issue: Replace pollueur by polleur

The word pollueur with a u after the ll is a noun meaning someone who makes pollution, the word polleur can be use as a translation for poller.

Here's the patch
```

# cat patchFR
--- fr-FR.po.orig       Thu Aug 27 02:21:27 2020
+++ fr-FR.po    Thu Aug 27 02:25:21 2020
@@ -3350,7 +3350,7 @@
 #: data_debug.php:677
 #, fuzzy
 msgid "Poller runs as"
-msgstr "Le pollueur fonctionne en tant que"
+msgstr "Le polleur fonctionne en tant que"

 #: data_debug.php:682
 #, fuzzy
@@ -9747,7 +9747,7 @@
 #: include/global_settings.php:203
 #, fuzzy
 msgid "Alternate Poller Path"
-msgstr "Autre voie d'acheminement du pollueur"
+msgstr "Autre voie d'acheminement du polleur"

 #: include/global_settings.php:208
 #, fuzzy
@@ -10775,12 +10775,12 @@
 #: include/global_settings.php:1047
 #, fuzzy
 msgid "Poller Sync Interval"
-msgstr "Intervalle de synchronisation des pollueurs"
+msgstr "Intervalle de synchronisation des polleurs"

 #: include/global_settings.php:1048
 #, fuzzy
 msgid "The default polling sync interval to use when creating a poller.  This setting will affect how often remote pollers are checked and updated."
-msgstr "L'intervalle de synchronisation d'interrogation par défaut à utiliser lors de la création d'un poller.  Ce paramètre affectera la fréquence de vérification et de mise à jour des pollueurs distants."
+msgstr "L'intervalle de synchronisation d'interrogation par défaut à utiliser lors de la création d'un poller.  Ce paramètre affectera la fréquence de vérification et de mise à jour des polleurs distants."

 #: include/global_settings.php:1055
 #, fuzzy
@@ -11564,7 +11564,7 @@
 #: include/global_settings.php:1715
 #, fuzzy
 msgid "Poller Logging Level for Cacti Reporting"
-msgstr "Niveau d'enregistrement des pollueurs pour les rapports Cacti"
+msgstr "Niveau d'enregistrement des polleurs pour les rapports Cacti"

 #: include/global_settings.php:1716
 #, fuzzy
@@ -13014,7 +13014,7 @@
 #: lib/data_query.php:369
 #, fuzzy
 msgid "No Index Changes Detected, Skipping Re-Index and Poller Cache Re-population"
-msgstr "Aucun changement d'index détecté, saut du ré-indice et re-population de l'antémémoire du pollueur."
+msgstr "Aucun changement d'index détecté, saut du ré-indice et re-population de l'antémémoire du polleur."

 #: lib/data_query.php:391
 #, fuzzy
@@ -15190,7 +15190,7 @@
 #: lib/installer.php:1965
 #, fuzzy
 msgid "Remote Pollers are used to access networks that are not readily accessible to the Primary site."
-msgstr "Les pollueurs distants sont utilisés pour accéder aux réseaux qui ne sont pas facilement accessibles au site principal."
+msgstr "Les polleurs distants sont utilisés pour accéder aux réseaux qui ne sont pas facilement accessibles au site principal."

 #: lib/installer.php:2020
 #, fuzzy
@@ -15255,7 +15255,7 @@
 #: lib/installer.php:2059
 #, fuzzy
 msgid "Remote Poller Variables"
-msgstr "Variables du pollueur distant"
+msgstr "Variables du polleur distant"

 #: lib/installer.php:2061
 #, fuzzy
@@ -15325,7 +15325,7 @@
 #: lib/installer.php:2186
 #, fuzzy
 msgid "For remote pollers, it is critical that the paths that you will be updating frequently, including the plugins, scripts, and resources paths have read/write access as the data collector will have to update these paths from the main web server content."
-msgstr "Pour les pollueurs distants, il est essentiel que les chemins que vous mettrez à jour fréquemment, y compris les plugins, les scripts et les chemins des ressources aient un accès en lecture/écriture car le collecteur de données devra mettre à jour ces chemins depuis le contenu du serveur Web principal."
+msgstr "Pour les polleurs distants, il est essentiel que les chemins que vous mettrez à jour fréquemment, y compris les plugins, les scripts et les chemins des ressources aient un accès en lecture/écriture car le collecteur de données devra mettre à jour ces chemins depuis le contenu du serveur Web principal."

 #: lib/installer.php:2192
 #, fuzzy
@@ -17147,7 +17147,7 @@
 #: poller.php:539
 #, fuzzy, php-format
 msgid "WARNING: Poller Output Table not empty for poller id %d.  Issues: %d, %s."
-msgstr "AVERTISSEMENT : La table de sortie des pollueurs n'est pas vide.  Problèmes : %d, %s."
+msgstr "AVERTISSEMENT : La table de sortie des polleurs n'est pas vide.  Problèmes : %d, %s."

 #: poller.php:562
 #, fuzzy, php-format
@@ -19140,7 +19140,7 @@
 #: utilities.php:345
 #, fuzzy
 msgid "Poller Information"
-msgstr "Renseignements sur le pollueur"
+msgstr "Renseignements sur le polleur"

 #: utilities.php:353
 #, fuzzy
@@ -19407,7 +19407,7 @@
 #: utilities.php:1739
 #, fuzzy
 msgid "Poller Cache Items"
-msgstr "Eléments du cache du pollueur"
+msgstr "Eléments du cache du polleur"

 #: utilities.php:1800
 msgid "Script"
```

### CODE REVIEW

**Comment by TheWitness** [comment]
Can you sync your repo with the latest 1.2.x branch to remove the conflicts?

**Comment by TheWitness** [comment]
Thanks for your efforts by the way!

**Comment by mikygee** [comment]
Hello,
I have absolutely no idea how to sync my repo with the 1.2 branch

**Comment by mikygee** [comment]
Maybe this patch is ok, I git cloned 1.2.x

```
# cat patchFR
--- fr-FR.po.orig       Fri Aug 28 01:32:51 2020
+++ fr-FR.po    Fri Aug 28 01:43:01 2020
@@ -3316,7 +3316,7 @@
 #: data_debug.php:680
 #, fuzzy
 msgid "Poller runs as"
-msgstr "Le pollueur fonctionne en tant que"
+msgstr "Le polleur fonctionne en tant que"

 #: data_debug.php:685
 #, fuzzy
@@ -9696,7 +9696,7 @@
 #: include/global_settings.php:203
 #, fuzzy
 msgid "Alternate Poller Path"
-msgstr "Autre voie d'acheminement du pollueur"
+msgstr "Autre voie d'acheminement du polleur"

 #: include/global_settings.php:208
 #, fuzzy
@@ -10716,12 +10716,12 @@
 #: include/global_settings.php:1038
 #, fuzzy
 msgid "Poller Sync Interval"
-msgstr "Intervalle de synchronisation des pollueurs"
+msgstr "Intervalle de synchronisation des polleurs"

 #: include/global_settings.php:1039
 #, fuzzy
 msgid "The default polling sync interval to use when creating a poller.  This setting will affect how often remote pollers are checked and updated."
-msgstr "L'intervalle de synchronisation d'interrogation par défaut à utiliser lors de la création d'un poller.  Ce paramètre affectera la fréquence de vérification et de mise à jour des pollueurs distants."
+msgstr "L'intervalle de synchronisation d'interrogation par défaut à utiliser lors de la création d'un poller.  Ce paramètre affectera la fréquence de vérification et de mise à jour des polleurs distants."

 #: include/global_settings.php:1046
 #, fuzzy
@@ -11438,7 +11438,7 @@
 #: include/global_settings.php:1627
 #, fuzzy
 msgid "Poller Logging Level for Cacti Reporting"
-msgstr "Niveau d'enregistrement des pollueurs pour les rapports Cacti"
+msgstr "Niveau d'enregistrement des polleurs pour les rapports Cacti"

 #: include/global_settings.php:1628
 #, fuzzy
@@ -12845,7 +12845,7 @@
 #: lib/data_query.php:356
 #, fuzzy
 msgid "No Index Changes Detected, Skipping Re-Index and Poller Cache Re-population"
-msgstr "Aucun changement d'index détecté, saut du ré-indice et re-population de l'antémémoire du pollueur."
+msgstr "Aucun changement d'index détecté, saut du ré-indice et re-population de l'antémémoire du polleur."

 #: lib/data_query.php:380
 #, fuzzy
@@ -15000,7 +15000,7 @@
 #: lib/installer.php:1940
 #, fuzzy
 msgid "Remote Pollers are used to access networks that are not readily accessible to the Primary site."
-msgstr "Les pollueurs distants sont utilisés pour accéder aux réseaux qui ne sont pas facilement accessibles au site principal."
+msgstr "Les polleurs distants sont utilisés pour accéder aux réseaux qui ne sont pas facilement accessibles au site principal."

 #: lib/installer.php:1995
 #, fuzzy
@@ -15065,7 +15065,7 @@
 #: lib/installer.php:2034
 #, fuzzy
 msgid "Remote Poller Variables"
-msgstr "Variables du pollueur distant"
+msgstr "Variables du polleur distant"

 #: lib/installer.php:2036
 #, fuzzy
@@ -15135,7 +15135,7 @@
 #: lib/installer.php:2161
 #, fuzzy
 msgid "For remote pollers, it is critical that the paths that you will be updating frequently, including the plugins, scripts, and resources paths have read/write access as the data collector will have to update these paths from the main web server content."
-msgstr "Pour les pollueurs distants, il est essentiel que les chemins que vous mettrez à jour fréquemment, y compris les plugins, les scripts et les chemins des ressources aient un accès en lecture/écriture car le collecteur de données devra mettre à jour ces chemins depuis le contenu du serveur Web principal."
+msgstr "Pour les polleurs distants, il est essentiel que les chemins que vous mettrez à jour fréquemment, y compris les plugins, les scripts et les chemins des ressources aient un accès en lecture/écriture car le collecteur de données devra mettre à jour ces chemins depuis le contenu du serveur Web principal."

 #: lib/installer.php:2167
 #, fuzzy
@@ -16941,7 +16941,7 @@
 #: poller.php:524
 #, fuzzy, php-format
 msgid "WARNING: Poller Output Table not empty for poller id %d.  Issues: %d, %s."
-msgstr "AVERTISSEMENT : La table de sortie des pollueurs n'est pas vide.  Problèmes : %d, %s."
+msgstr "AVERTISSEMENT : La table de sortie des polleurs n'est pas vide.  Problèmes : %d, %s."

 #: poller.php:547
 #, fuzzy, php-format
@@ -18867,7 +18867,7 @@
 #: utilities.php:329
 #, fuzzy
 msgid "Poller Information"
-msgstr "Renseignements sur le pollueur"
+msgstr "Renseignements sur le polleur"

 #: utilities.php:337
 #, fuzzy
@@ -19125,7 +19125,7 @@
 #: utilities.php:1655
 #, fuzzy
 msgid "Poller Cache Items"
-msgstr "Eléments du cache du pollueur"
+msgstr "Eléments du cache du polleur"

 #: utilities.php:1716
 msgid "Script"
@@ -19134,11 +19134,11 @@
 #: utilities.php:1837 utilities.php:1842
 #, fuzzy
 msgid "SNMP Version:"
-msgstr "Version de SNMP"
+msgstr "Version de SNMP :"

 #: utilities.php:1838
 msgid "Community:"
-msgstr "Quartier :"
+msgstr "Communauté :"

 #: utilities.php:1839 utilities.php:1843
 #, fuzzy
@@ -19147,7 +19147,7 @@

 #: utilities.php:1843
 msgid "User:"
-msgstr "Utilisateur:"
+msgstr "Utilisateur :"

 #: utilities.php:1846
 #, fuzzy
```

**Comment by TheWitness** [comment]
Then, send the modified *.po file to developers @ cacti dot net, and we will provide attribution when we commit it.  I answered your question about "#, fuzzy" in the other thread.

**Comment by TheWitness** [comment]
The ./build_gettext.sh will update the po files with the latest strings too.  So, before you go too long, you might want to run that.

**Pull request merged**
