### PR TITLE
New Device template - Aruba Instant cluster

### PR DESCRIPTION
**Pull request by xmacan**
Small piece of #2379

Device template for Aruba wifi instant cluster. if it's okay, I'll prepare more, for example:
Aruba wifi controller, HP MSM wifi controller, Fortinet Fortigate firewall, Mikrotik, Synology NAS , ESXi, ...

### CODE REVIEW

**Comment by bmfmancini** [comment]
This is such a good Idea! 
I have a bunch of custom snmp queries I have made also but how would you include the graph templates needed by default ?

i.e BGP monitoring for Cisco I have a template with a snmp_query but would also need the graph template to be imported

**Comment by netniV** [comment]
When you export the template, it should export everything it needs.

**Comment by bmfmancini** [comment]
Sorry to clarify

I mean how can we include it as part of the default installation?

**Comment by netniV** [comment]
We tend to create packages for the templates.  If you look at install/templates, I am sure they are all tar.gz that we create using an internal packaging script.

**Comment by xmacan** [comment]
Sorry, I made someting bad. I will create new pull request

**Pull request closed without merging**
