### PR TITLE
Fixed #3563: Correct errors due to orphan column

### LINKED ISSUE #3563: Current orphan handling disrupts graphing transient indexes
# Describe the bug

If you have transient indexes in your system, the impact on re-indexing can disrupt graphing and generate excessive log messages, and becomes a burden to keep up with.

## To Reproduce

1. Create a Data Query where indexes periodically leave the system, like a wireless router

2. Re-index and note a entries leave the system, the graphs stop working and warnings are generated periodically

## Expected behavior

Cacti should mark them as orphans so that they are traceable, but should not bother the admin with excessive logging.

### PR DESCRIPTION
**Pull request by ddb4github**
lots of "Error: Duplicate column name 'orphan'" from parallel process 'poller_reindex_hosts.php':
 - Add column 'orphan' during 1.2.13 upgrade
 - Remove function 'add_orphan_support'

### CODE REVIEW

**Comment by TheWitness** [comment]
Make this for 1.2.14 please.

**Comment by netniV** [comment]
I am confused as this seems to be removing functionality yet added a database column?  Unless my tired eyes are just not reading this right.

**Comment by ddb4github** [comment]
> I am confused as this seems to be removing functionality yet added a database column? Unless my tired eyes are just not reading this right.

#3563 dynamically add new column data_local.orphan for data source related access(including CLI)
If user upgrade Cacti to 1.2.13 as case below:
1. Upgrade to 1.2.13(by CLI/Web)
2. Do not access any data source related feature by web
3. Cron exec poller.php-->(multiple)poller_reindex_hosts.php to add new graphs.
4. The first poller_reindex_hosts.php will successfully add new column data_local.orphan.
    Other poller_reindex_hosts.php will report error

**Comment by TheWitness** [comment]
@ddb4github, 1.2.13 has already been released.  Can you please make this change for 1.2.14?

**Review by netniV — CHANGES_REQUESTED** [review]
Changes themselves look OK.  However, if we are adding a new column, the cacti.sql should be updated with a new audit so that new databases contain the column.

**Review by netniV — APPROVED** [review]

**Pull request merged**
