### PR TITLE
Fixed several typo in php file header

### PR DESCRIPTION
**Pull request by ddb4github**

### CODE REVIEW

**Comment by TheWitness** [comment]
I don't think a changelog is necessary for this one.

**Comment by netniV** [comment]
Technically, a lot of those comments we should not have corrected since we are supposed to distribute the module as-is and that is their own wording.

**Comment by ddb4github** [comment]
> Technically, a lot of those comments we should not have corrected since we are supposed to distribute the module as-is and that is their own wording.

Actually, I check these sentence  from Cacti because I found  them from  "plugin_thold/thold_daemon.php" at first.

**Comment by netniV** [comment]
Copy and paste jobbie it sounds like.  No issues fixing those in our code, they should be corrected.

**Pull request merged**
