### PR TITLE
Added support for showing business hours

### PR DESCRIPTION
**Pull request by thurban**
Added Basic functionality for showing business hour areas.
- Added new global config settings in the visual tab to allow:
  - Hiding of business hours for weekends ( Saturday/Sunday ) - Defaults to showing them
  - Setting the Start/End time for business hours ( Defaults to 08:00  - 18:00 )
  - Setting for the color of the business hours (Defaults to ccccccff a light gray)
  - Setting for disabling the business hours feature
- Added new rrd function to the lib/rrd.php file
- Pull request for feature #4874

### CODE REVIEW

**Comment by thurban** [comment]
Any news on this ?

**Comment by TheWitness** [comment]
Thomas, I'll merge it in a few days.  I pushed it on the schedule to 1.2.23.  Right now, I'm taking a few days off to relax.

**Comment by thurban** [comment]
Cool. Is there anything I could work on ? Like the poller/msg queue stuff. When your back, let's scheduled a call if you don't mind.  would like to get more involved again

**Comment by TheWitness** [comment]
Sure, I times the drive, it's around 3 hours...  It's that or to fly in.

**Comment by TheWitness** [comment]
Send me a DM on the project side.

**Pull request merged**
