### PR TITLE
Merge3392back

### PR DESCRIPTION
**Pull request by YongBoLiu**
Merge issue #3392 back to 1.2.x, as we did #3406 in develop branch.

### CODE REVIEW

**Comment by TheWitness** [comment]
Going to merge this, but I'll need you to submit another pull against develop once 4018 is merged.

**Comment by YongBoLiu** [comment]
Ok, the php-cs-fixer seems not works well with PHP 5.4.

**Comment by TheWitness** [comment]
Good to know.  The 1.3 branch is going full php73+ now.  I'm using the remi repos.

**Comment by TheWitness** [comment]
There is also the RedHat SCL, for RHEL7, but the way it sets up PHP seems unorthodox. You have to activate it like VirtualENV, and Anaconda.

**Comment by YongBoLiu** [comment]
Good to know. Thanks @TheWitness

**Pull request merged**
