### PR TITLE
add ip to login log message

### PR DESCRIPTION
**Pull request by xmacan**
Request from the forum. Adding an IP address to the login log

### CODE REVIEW

**Comment by TheWitness** [comment]
What about 1.2.x?

**Comment by xmacan** [comment]
You approved the same thing for 1.2.x 2 day ago :-)
https://github.com/Cacti/cacti/pull/5772

**Comment by TheWitness** [comment]
Did I already cherry pick it then?

**Comment by TheWitness** [comment]
https://github.com/Cacti/cacti/commit/448b6778f26e40f005f167b5822e443cd5ef5e5b

**Pull request merged**
