### PR TITLE
Quotes problem using RRDtool 1.4.5 and Windows environment

### PR DESCRIPTION
**Pull request by xbolshe**
Quotes " ' " do not work in Windows environment.
Some tags use " ' ", some tags use ' " '.

Windows environment: Windows Server 2008 R2 English

Samples with the problem:

rrd145_2

rrd145

### CODE REVIEW

**Comment by xbolshe** [comment]
I used this RRDtool: http://www.cacti.net/downloads/packages/Windows/rrdtool-1.4.5-win32-vc2008.rar

**Comment by xbolshe** [comment]
Mantis: http://bugs.cacti.net/view.php?id=2678

**Comment by cigamit** [comment]
Okay, this has to be specific to Windows.  Are you able to make a patch?  The escape character is the backslash.

**Comment by cigamit** [comment]
Okay, see you uploaded a patch.  Did not catch that.

**Pull request merged**
