### PR TITLE
Add script to create/check files with md5sum

### PR DESCRIPTION
**Pull request by DavidLiedke**
#349 

I create the script in the /cli folder. Is this okay ?

The script generates the .md5sum file in root folder. 

@ronytomen

### CODE REVIEW

**Comment by netniV** [comment]
It's a good start but I think it needs to exclude more items.  Probably those that are within the .gitignore because you will end up including the .RRA and logs folders. The reason being if someone wanted to run this against their own files to see whats changed this would allow them to do so.

Additionally, and this is a personal preference not one that's necessary, I would probably have dropped the .sh extension and added a verify hash script too.  That would take an existing hash file and check all the files that are within it.  If you don't feel up to, I can throw that together for you.

**Comment by DavidLiedke** [comment]
Good idea!

**Comment by DavidLiedke** [comment]
**cli/create_md5sum**
- Check if executed in the root folder
- Give user feedback

Following folders are exluced:
.git/
cache/
log/
plugins/
rra/
scripts/

**cli/check_md5sum**
- Check if executed in the root folder
- Give user feedback
- Only Errors are listed

**Comment by netniV** [comment]
Some good work.  My next suggestions and feel free to ignore them as they are just ideas I've had:

- Rather than using a specific temporary name, use `mktemp` to generate a random name to prevent the (unlikely) clashes of multiple uses.
- Ignore .htaccess in all folders since an admin can modify these depending on their web server requirements
- After seeing the commit above, do not exclude scripts since that has some files distributed with cacti
- Allow a command parameter to specify the root folder?  Can even default the folder path to the output of pwd or since you specify BASH as the script processor, use $BASH_SOURCES if applicable.

Separately, I'm wondering if we should allow plugins via an extra option, since a user may wish to verify those.

**Comment by netniV** [comment]
We probably need a Win32 version of this too since this will only run under Bash on Linux currently.

**Comment by DavidLiedke** [comment]
- [x] Rather than using a specific temporary name, use mktemp to generate a random name to prevent the (unlikely) clashes of multiple uses.

- [x] Ignore .htaccess in all folders since an admin can modify these depending on their web server requirements

- [x] After seeing the commit above, do not exclude scripts since that has some files distributed with cacti

For the rest i need more time.

**Comment by cigamit** [comment]
Yes, a .sh script just limits us to *Nix.  This would be better if it was PHP like the rest of Cacti.  Also, we already do this if you have multipollers enabled, look at the DB Table "poller_resource_cache".  It has an MD5 Sum of every file in Cacti folder, the last time it was updated and the actual contents.

**Comment by DavidLiedke** [comment]
Okay i will try to convert the bash script to a php script.

**Comment by cigamit** [comment]
Guys, going to spend some time today merging things.  I will wait till there is a PHP script before merging this one.

**Comment by netniV** [comment]
if @DavidLiedke hasn't comment by the morning, I will convert it over.  My only issue being some of the linux specific commands may not be available.

**Comment by netniV** [comment]
I have an almost working version now that uses a single php file like md5sum would.

**Comment by cigamit** [comment]
@DavidLiedke, since @netniV has created this in PHP, I will close here.  I've asked him to remove the .md5sum file though.  I think that Rony can add that to the packaging process for release unless you think we need to update this like we do the *.pot file.

**Pull request closed without merging**
