### PR TITLE
Advanced Ping graph template and script

### PR DESCRIPTION
**Pull request by jdcoats**
The original advanced ping 2.2 graph template and ss_fping.php with split replaced by explode and ereg replaced by preg_match 
[cacti_graph_template_ping_advanced_ping_v2_2.zip](https://github.com/Cacti/cacti/files/2889504/cacti_graph_template_ping_advanced_ping_v2_2.zip)
[ss_fping.zip](https://github.com/Cacti/cacti/files/2889506/ss_fping.zip)

### CODE REVIEW

**Comment by netniV** [comment]
I'm going to close this pull request as something is wrong with it.  It looks like you are attempting to merge from the master branch back into the main branch

**Comment by jdcoats** [comment]
When I try to create a pull request It makes me select master or 1.2, Either im doing something wrong or its broken. I can’t create in develop

Dan Coats
IT/Network VoIP Engineer
Tallahassee Memorial Healthcare
Office 850-431-7014
Cell 850-567-2201
dan.coats@tmh.org<mailto:dan.coats@tmh.org>

*CONFIDENTIALITY NOTICE* The information contained in this email message is intended only for the personal and confidential use of the designated recipient(s) named above. This message may be an attorney/client or physician/patient communication, and as such, is privileged and confidential. If the reader of this message is not the intended recipient, you are hereby notified that you have received this document in error, and that any review, dissemination, distribution, or copying of this message is strictly prohibited. If you have received this email communication in error, please notify me immediately by telephone.

**Comment by netniV** [comment]
Where is your original branch?

**Comment by jdcoats** [comment]
I don’t know what you mean by my original branch so I’m obviously doing it wrong. I’m just suggesting that the Graph Template and Script be added to cacti.

Dan

**Comment by netniV** [comment]
OK, so the problem here is that you are trying to create a pull request.  A pull request is when you have code in a branch on your own repository that you want us to pull into ours.  

For standard issues or enhancement requests, create an issue not a pull request.

**Pull request closed without merging**
