### PR TITLE
Fix #3392, Add hooks for Devices page to customize the filter and col…

### LINKED ISSUE #3392: Customize filters and host list in Console->Devices page
**Is your feature request related to a problem? Please describe.**
We need add a special filter on Console->Device page, such as cluster to filter the hosts. I have to change the host.php code. And when the cacti upgrade, the filters missing. 

**Describe the solution you'd like**
Add some hooks to show the customize filters from plugins, and add hook to some customer columns in the host list.

The hooks may be as below,
api_plugin_hook('device_filter_start');
api_plugin_hook_function('device_display_text', $display_text);
api_plugin_hook_function('device_table_start', $hosts);

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by YongBoLiu**
rebase #3396 pull request to the Develop branch

### CODE REVIEW

**Comment by netniV** [comment]
If we are adding a start hook, should we not also add an end one? Just to complete the set.

**Comment by YongBoLiu** [comment]
@netniV yes, the end one should be added correspondingly. I added the device_table_start hook.

For the device_table_start one, it is really for replacement, so I changed the name from device_table_start to device_table_replace. Because plugin maybe add columns in the begin, in the end and in the middle of the table.

Is that ok for you? What do you think? Thanks for the comments.

**Comment by netniV** [comment]
The replace name is better if that's its given functionilty. 👍

**Comment by YongBoLiu** [comment]
@netniV Is the code ok for you? When can this PR be authorized and be merged. Thanks.

**Comment by TheWitness** [comment]
This does look better.

**Pull request merged**
