### PR TITLE
Feature: Allow searching of SNMP Index in View Data Query Cache

### PR DESCRIPTION
**Pull request by netniV**
This pull request allows the searching of SNMP Index in View Data Query Cache.  By default the search does not include the index (as per current functionality).  When ticked, includes the SNMP index in the search.

If there are no MIBs for the OID being searched against, this will likely result in the same rows being listed when the checkbox is ticked and unticked.  However, if an MIB is present then the name is displayed instead of the OID.  As a result of this, any row not showing the index value in the columns other than index will only present only when the checkbox is ticked.

### CODE REVIEW

**Comment by netniV** [comment]
Not 100% sure I implemented this right, but it works 👍

**Comment by cigamit** [comment]
I don't think we need the checkbox.  Can you just update the SQL and remove the checkbox?

**Comment by netniV** [comment]
The reason for the checkbox is that you may not wish to include the index in the search which is the current functionality.  Searching for 10, for example would currently only show those entries where something had a value containing 10 such as an OID without a MIB name.  If we don't offer the tick box, it would also show all entries that had index 10 against it, which could be a quite a few.

**Comment by netniV** [comment]
Out of interest, I noticed none of this code is using the form API code.

**Comment by cigamit** [comment]
Yea, it's a bit involved.  We can always look at re-factoring, but not for 1.1.36.

**Comment by cigamit** [comment]
Alright, I'll merge, but making one change first.  Checkbox first, label second.

**Comment by netniV** [comment]
I tried that and it looks wrong as it blends with the next field label.

**Pull request merged**
