### PR TITLE
Remove extra parameter from SELECT

### PR DESCRIPTION
**Pull request by Cosmologist**
Id parameter was not used

### CODE REVIEW

**Comment by sd3m0n** [comment]
I've upgraded from 1.1.10->1.1.12

After removing "pc.id" from /lib/plugins.php I have this:

2017/07/07 21:27:29 - CMDPHP SQL Backtrace: (/clog.php: 27 include)(/include/auth.php: 27 include)(/include/global.php: 357 api_plugin_hook)(/lib/plugins.php: 60 db_fetch_assoc_prepared)(/lib/database.php: 384 cacti_debug_backtrace)
2017/07/07 21:27:29 - DBCALL ERROR: SQL Assoc Failed!, Error: Column 'id' in order clause is ambiguous
2017/07/07 21:27:29 - DBCALL ERROR: SQL Assoc Failed!, Error:1052, SQL:'SELECT ph.name, ph.file, ph.function FROM plugin_hooks AS ph LEFT JOIN plugin_config AS pc ON pc.directory = ph.name WHERE ph.status = 1 AND hook = ? ORDER BY id ASC'

And so on...
Returning back "pc.id" removed errors but now the log is completely clear... nothing about poller working process.

**Comment by sd3m0n** [comment]
I think it must be:

$result = db_fetch_assoc_prepared('SELECT ph.name, ph.file, ph.function
                FROM plugin_hooks AS ph
                LEFT JOIN plugin_config AS pc
                ON pc.directory = ph.name
                WHERE ph.status = 1 AND hook = ?',  array($name), true);

But the log is still empty.

**Comment by reboot1983** [comment]
I don't agree. Since `pc.id` has been removed, the `ORDER BY id ASC` is now ambiguous. 
So, this has to be `ORDER BY pc.id ASC`

**Comment by sd3m0n** [comment]
Yes I agree then. ORDER BY pc.id is OK

**Pull request merged**
