### PR TITLE
1.2.x - check if query result contains requested column

### PR DESCRIPTION
**Pull request by bernisys**
This should reduce the "undefined index" messages during poller-recovery and log the requested column name.
Please evaluate if this is sufficient or if it needs some deeper considerations.

### CODE REVIEW

**Comment by TheWitness** [comment]
Yea, this looks good.  Extra check.

**Comment by TheWitness** [comment]
@bernisys, need a CHANGELOG entry please.

**Comment by TheWitness** [comment]
I don't think we need this.  There was a problem solved in this commit.  https://github.com/Cacti/cacti/commit/0f987ca15ae35ab39fc94f23176405ae28623ea3

**Comment by bernisys** [comment]
I think it doesn't hurt to keep that extra check, as related issues might occur in future and at least this makes them visible in more detail. Regarding CHANGELOG entry how about something like: "add sanity check query result"?

**Pull request closed without merging**
