### PR TITLE
issue #1296: CactiErrorHandler now ignores suppressed errors

### PR DESCRIPTION
**Pull request by netniV**
This corrects issues where the @ symbol is being used but the error handler still reports the problems, thus spams the log with entries that would otherwise have been suppressed.

### CODE REVIEW

**Comment by cigamit** [comment]
Somehow I think this defeats the purpose of the error handler.  We want to disable plugins when they behave badly an if the web server is setup to suppress all errors, they would continue to error out.  Am I wrong here?

**Comment by netniV** [comment]
Then what we should do is force erring be setting error_reporting in global.php so its automatically on.

**Comment by netniV** [comment]
The alternative is that plugin authors end up overriding the handle to fix the suppression problem and then we never know.

**Comment by cigamit** [comment]
I know of several old script server calls that set `error_reporting(0);` in them.  Having to deal with these old scripts is going to be fun.  There may be some plugins doing this as well.  Let me do some additional testing with this in the mean time.

**Comment by netniV** [comment]
MacTrack is a plugin that uses the @ functionality on an array to suppress missing index warnings which I think is wrong. 

But then we you get warnings from system functions that have the @ at the front and are actively documented to use this to suppress the warning it makes standard functionality wrong to. 

Really I think PHP handles this all wrong as it should let the error handler know it’s a temporary suppression in action.  But there is no way we can get that sorted lol

**Comment by cigamit** [comment]
I thought that for those calls, I uninstalled the default Cacti Error Handler and added MacTracks own error handler so that it could handle/ignore those errors itself.  I might have missed something though.  This is the way I would prefer it.  After MacTrack is done, it would simply exit or restore the Cacti Error Handler.

**Comment by netniV** [comment]
The other problem is for code such as the snmpwalk when done via PHP. Although it's 'suppressed' by using the @ symbol, it's still logged.  That's what I was seeing the other day thinking it wasn't working in #1293 when actually it was, it was just also warning me about it too.

**Pull request merged**
