### PR TITLE
More fixing for #3912 for graph csv export in Time Graph View

### PR DESCRIPTION
**Pull request by ddb4github**
Fixed: More fixing for #3912 for graph csv export in Time Graph View

### CODE REVIEW

**Comment by TheWitness** [comment]
Very good catch @ddb4github.

**Comment by ddb4github** [comment]
@TheWitness PR might lost because I delete branch during checking/pending.
Could you reopen this PR? or I create another PR for this diff

**Comment by TheWitness** [comment]
Create another.  Note @netniV is releasing tomorrow. So, need to know if this is critical. ASAP

**Comment by TheWitness** [comment]
Create another.  Reference the changelog if duplicate.

**Comment by ddb4github** [comment]
> Create another. Note @netniV is releasing tomorrow. So, need to know if this is critical. ASAP

By process, we will not switch 1.2.15 to `1.2.16, just select some important fixing. So nothing is critical
I'll create a new as soon

**Pull request closed without merging**
