### PR TITLE
Fix Boost undefined rrd_name error

### PR DESCRIPTION
**Pull request by simnv**

### CODE REVIEW

**Comment by cigamit** [comment]
I'm not happy with this merge request.  The variable will always be set, the question is will it be empty/blank.  Can you please reverts the code, and the post the output of the query on line: 973?

**Comment by simnv** [comment]
Here you go:
```
2017-01-07 22:20:08 - DBCALL DEVEL: SQL Assoc: "SELECT data_source_name, rrd_path  FROM data_template_rrd AS dtr  INNER JOIN poller_item AS pi  ON (pi.local_data_id = dtr.local_data_id  AND (pi.rrd_name = dtr.data_source_name OR pi.rrd_name = ''))  WHERE dtr.local_data_id = ?  ORDER BY data_source_name ASC"
2017-01-07 22:20:08 - BOOST PROGERR: ERRNO:'8' TYPE:'Notice' MESSAGE:'Undefined index: rrd_name' IN FILE:'/opt/cacti/lib/boost.php' LINE NO:'987'
2017-01-07 22:20:08 - BOOST PROGERR: ERRNO:'8' TYPE:'Notice' MESSAGE:'Undefined index: rrd_name' IN FILE:'/opt/cacti/lib/boost.php' LINE NO:'987'
```

$ds_names is requested with only two columns: data_source_name and rrd_path, and then $ds_name is checked for "rrd_name", which is absent.

**Comment by cigamit** [comment]
Okay, that is a different problem then.  I'll close this one.  Fix will be in shortly.

**Comment by cigamit** [comment]
Thanks for locating this.

**Pull request closed without merging**
