### PR TITLE
Make LDAP errors consistent across functions

### PR DESCRIPTION
**Pull request by netniV**
This update introduces LdapError which provides common error codes and messages between Ldap functions.

### CODE REVIEW

**Comment by cigamit** [comment]
Fails on php5.4-php5.6

**Comment by netniV** [comment]
Ah yeah, it's because of the 
```php 
int param = 0
```
in the function header.  I'll have to get a php5.4 environment going so I can see these errors before I commit.

**Comment by cigamit** [comment]
Were you planning on fixing this?

**Comment by netniV** [comment]
Yes.  I think the Scheduler code, etc may have a similar issue too

**Comment by netniV** [comment]
Weird part is that it passes syntax checks but fails at run time. I'm going to finish my CentOS 6.9 setup next week so I can test against these kinds of things.

**Comment by netniV** [comment]
Assuming that 7.4 is still using PHP 5, it would.  That's the strange thing. PHP 7 is fine with it, in fact, I don't really understand why PHP 5 moans only at runtime given that the definition of the function defines it as an int and assigns the value... it already should know it won't like it. But hey ho.

**Pull request merged**
