### PR TITLE
Feature 1734 - Visual enhancements to RRD error message when file not found

### PR DESCRIPTION
**Pull request by netniV**
This commit adds a new feature (#1734 ) to visually enhance the RRD error message when the RRD file is not found or accessible.  It also corrects an issue with the is_resource_writable() function.

## RRA directory is not writable:
image

## RRA directory is writable, RRA file is not writable:
image

## RRA directory is writable, RRA file is writable but not created:
image

### CODE REVIEW

**Comment by jackouille-ch** [comment]
Ok better now:
image

But RRD name is missing

**Comment by netniV** [comment]
It should be.  You have a bigger problem.  The website doesn't seem to have update capabilities on the RRA directories.  This may be because it needs a sticky bit to ensure write access on newly created folders at group level.  But, for now, it's good to see it's work so I'm going to close this. (Don't forget to update your permissions).

**Comment by jackouille-ch** [comment]
My permissions are correct:
drwxr-xr-x 2 cacti apache    126 Jul 23 09:34 162
drwxr-xr-x 2 cacti apache    112 Jul 26 15:51 164
drwxr-xr-x 2 cacti apache     96 Jul 23 09:34 165
drwxr-xr-x 2 cacti apache   4096 Jul 23 09:34 166
drwxr-xr-x 2 cacti apache   4096 Jul 23 09:34 167
drwxr-xr-x 2 cacti apache   4096 Jul 23 09:34 168
drwxr-xr-x 2 cacti apache   4096 Jul 23 09:34 169
drwxr-xr-x 2 cacti apache   4096 Jul 23 09:34 170

But I create a graph that isn't possible on the device, just for testing purpose.

**Comment by jackouille-ch** [comment]
Ok changed, thanks ;-)

**Comment by netniV** [comment]
Error message changed?

**Comment by jackouille-ch** [comment]
Yes perfect:
image

**Comment by netniV** [comment]
The good thing is, that error is actually localizable (well localisable to me haha).

**Comment by jackouille-ch** [comment]
So for my you can close it. Many thanks.

**Comment by netniV** [comment]
Well this is the PR, we leave it open until it's merged 👍

**Comment by netniV** [comment]
And now it's closed :)

**Pull request merged**
