### PR TITLE
When creating RRD error image, font may not exist

### PR DESCRIPTION
**Pull request by xmacan**

### CODE REVIEW

**Review by netniV — CHANGES_REQUESTED** [review]
Should be !empty and there's no change log for this ?

**Comment by xmacan** [comment]
> Should be !empty and there's no change log for this ?
Maybe problem with my installation (FreeBSD). Dejavu is installed. 
[pm@kaktus ~]$ locate DejaVuSans.ttf
/usr/local/share/fonts/dejavu/DejaVuSans.ttf
/usr/local/share/fonts/dejavu/DejaVuSans.ttf.pkgsave

I haven't investigated why $dejavu_paths is empty or without Sans.

**Comment by ddb4github** [comment]
@xmacan Could u add one line for FreeBSD:
```diff
diff --git a/include/global_arrays.php b/include/global_arrays.php
index 56bc6e033..e8506e4d0 100644
--- a/include/global_arrays.php
+++ b/include/global_arrays.php
@@ -2805,6 +2805,7 @@ if ($config['cacti_server_os'] == 'unix') {
                '/usr/share/fonts/dejavu/', //RHEL/CentOS
                '/usr/share/fonts/truetype/', //SLES
                '/usr/share/fonts/truetype/dejavu/', //Ubuntu
+               '/usr/local/share/fonts/dejavu/', //FreeBSD
                __DIR__ . '/fonts'  //Build-in
        );
 } else {
```

**Comment by TheWitness** [comment]
@ddb4github, once confirmed, can you file a separate pull request? You can reference the original ticket.

**Pull request merged**
