### PR TITLE
Fix for Issue #1246

### PR DESCRIPTION
**Pull request by netniV**
This adds more information to api_device_ping_device()'s SNMP Error output to allow better diagnositics of issues noted in #1246

### CODE REVIEW

**Comment by cigamit** [comment]
This will not get merged until after the release tomorrow night.  So, there is time to improve the error display.

**Comment by cigamit** [comment]
If you can get this done in the next few hours, we can still make 1.1.32.  Can you modify the pull request to check if the error is non '', and output the real error?

**Comment by cigamit** [comment]
If snmp_session is false, it means the device has no snmp or can not be reached, otherwise, check the errors.  Sorry about the confusion.

**Comment by cigamit** [comment]
Update the CHANGELOG.  Make it for 1.1.32.  Thanks!

**Comment by netniV** [comment]
image

**Pull request merged**
