### PR TITLE
Print the DS ID

### PR DESCRIPTION
**Pull request by rlaager**
add_datasource.php doesn't print the DS ID. This is a quick patch that prints it out in a format similar to how add_graphs.php does it. Feedback welcome.

### CODE REVIEW

**Comment by rlaager** [comment]
Updated as requested.

**Comment by TheWitness** [comment]
This is still targted improperly to the develop branch.  We need it pointed to the 1.2.x branch.  I'm going to close, just clone the 1.2.x branch and re-open in that branch.  I'll do the same with the other.

**Comment by TheWitness** [comment]
If you are using the GitHub desktop, you simply need to fork whatever version, which you have already done, then switch the branch to 1.2.x and carry your changes forward to that branch, and open a new pull request.

**Comment by rlaager** [comment]
Yeah, I'm also not sure how to change the target of the pull request. The commit itself was correctly rebased on 1.2.x. I just opened a new PR for the correct target branch as you suggested.

**Pull request closed without merging**
