### PR TITLE
Paw css - add few pixels 

### PR DESCRIPTION
**Pull request by xmacan**
My problem is showed here. It is problem on Linux/Firefox
[Záznam obrazovky z 2024-09-10 14-54-32.webm](https://github.com/user-attachments/assets/2d69499b-ceb3-4dcc-a24c-68ae3f9b51ab)

With fix:
image

### CODE REVIEW

**Comment by xmacan** [comment]
the cursor is not visible on the record but it is problematic use reload icon or checkboxes. slider overlays controls

**Comment by TheWitness** [comment]
I'm good with this, but can you evaluate the other themes too?

**Comment by browniebraun** [comment]
I agree, would be good if you can check the other themes, too. Please exclude MidWinter. Thanks
-Andi

**Comment by xmacan** [comment]
OK, I will check all themes (- midWinter)

**Pull request merged**
