### PR TITLE
Fix for issue #1292: browser caching of javascript and css files

### PR DESCRIPTION
**Pull request by netniV**
This corrects issues found in #1292 where browser caching of javascript and css files can cause issues.

### CODE REVIEW

**Comment by netniV** [comment]
If you think you need some mods to this in the next hour or two, I am going to be busy.  So feel free to push away or it'll have to wait for the next release.

**Comment by cigamit** [comment]
Looks good with a few issues:

* Functions get_md5_include_js() and get_md5_include_css() should be using return and not echo.  You are doing the print in the parent which is desirable.
* Function get_md5_include_css() has some debug code in it writing to /tmp.

Otherwise, looks real good.

**Comment by cigamit** [comment]
Would you I guess I can mod on the fly if you are okay.

**Comment by cigamit** [comment]
Just fixed everything up.  Merging now.

**Comment by netniV** [comment]
Ah, yeah I had it that way originally, switched it briefly to debug but missed changing it back as the output was still being printed lol.  Hopefully, I didn't leave any `file_puts_content()` lying around too.

**Comment by cigamit** [comment]
I'm doing the QA and regression right now.  Found a few additional changes.  Working on it.

**Comment by netniV** [comment]
I was thinking further on this as to whether we only really needed one hash per release.  Admittedly, helps more with the DEV work to have a hash per file as long as we restart the session we are using.

**Comment by cigamit** [comment]
I have to talk to Rony about this.  It should be committed right before release like the cacti_version file.

**Pull request merged**
