### PR TITLE
Undefined variable error may sometimes occur when dealing with RRD output

### PR DESCRIPTION
**Pull request by MSS970**
Update rrd.php missing variable $okpos

### CODE REVIEW

**Comment by TheWitness** [comment]
Can you redo this for 1.2.x branch or is it fine there?

**Comment by MSS970** [comment]
I have been using Cacti 1.3 (Dev) for long time on Windows and did not test this issue on 1.2.x

**Comment by MSS970** [comment]
I presume it is the same issue in Cacti 1.2.x, just checked the 1.2.x branch:

function rrdtool_trim_output(&$output) {
	global $config;

	/* When using RRDtool with proc_open for long strings
	 * and using the '-' to handle standard in from inside
	 * the process, RRDtool automatically appends stderr
	 * to stdout for batch programs to parse the output
	 * string.  So, therefore, we have to prune that
	 * output.
	 */
	if ($config['cacti_server_os'] == 'win32') {
		$output = rtrim($output, "OK \n\r");
/* MSS:  missing variable here */ 
	} else {
		$okpos = strrpos($output, 'OK u:');
		if ($okpos !== false) {
			$output = substr($output, 0, $okpos);
		}
	}
}

**Comment by TheWitness** [comment]
Okay, I fixed this in 1.2.x and will cherry pick into 1.3 shortly.

**Pull request closed without merging**
