### PR TITLE
Fixed #2949: change width of 'moveArrowNone' to 8.75 that is up/down …

### LINKED ISSUE #2949: MoveArrow icon not align in some pages
**Describe the bug**
MoveArrow icon not align in some pages

**To Reproduce**
1. Go to Console-->Configuration-->Plugins
2. Click on column header of 'Load Order'
3. Scroll down to page bottom
4. Check "Move Up' icon alignment

**Screenshots**
image

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: FireFox
 - Version: 60

### PR DESCRIPTION
**Pull request by ddb4github**
Fixed #2949: change width of 'moveArrowNone' to 8.75 that is up/down icon width

### CODE REVIEW

**Review by TheWitness — APPROVED** [review]
Looks good to me.

**Review by netniV — COMMENTED** [review]
I can't say that I've noticed this issue so makes me wonder if it comes down to fonts/images being used to create the up/down arrow.  Shouldn't the width for each moveArrowXXX class be fixed rather than applying padding to simulate the width when not present?

**Review by cigamit — APPROVED** [review]

**Comment by cigamit** [comment]
We should move these to Glyph s in 1.3.  For now, let's just commit.

**Comment by netniV** [comment]
> We should move these to Glyph s in 1.3. For now, let's just commit.

Best make an enhancement request then 👍

**Pull request merged**
