### PR TITLE
Improve compatibility with ping under FreeBSD

### PR DESCRIPTION
**Pull request by xmacan**

### CODE REVIEW

**Comment by TheWitness** [comment]
@xmacan you need to make a check for /sbin/ as on Standard Linux, ping6 is in /usr/sbin and it's not in the apache users path.  Can you do that?

**Review by TheWitness — CHANGES_REQUESTED** [review]
You must put a test to the ping6 location as in RH, Rocky, CentOS, Alma, it's in /usr/sbin/ and that path is not in Apache's path.

**Comment by TheWitness** [comment]
ChangeLog too. ;)

**Comment by xmacan** [comment]
My code is working. On freebsd is right location /sbin/ping6. 

I see a different problem there. Check ping.php code on line 195 - there is test  file_exists('/bin/ping6') but if condition is true, called is
/usr/sbin/ping6

**Review by TheWitness — CHANGES_REQUESTED** [review]
We need a check for /sbin/ping6 as in Red Hat, Alma, CentOS, and Rocky, '/sbin' is NOT in the apache accounts path.

**Comment by TheWitness** [comment]
Also, note that on those same operating systems, they have unified the timeout setting to be the same at ping using the `-W timeout`, not -t or -x.

**Comment by TheWitness** [comment]
How about just `ping -6`?

**Comment by TheWitness** [comment]
Please check the updates.  I'm merging this now.

**Review by TheWitness — APPROVED** [review]

**Pull request merged**
