### PR TITLE
re:#5687 - Add support for Cisco equipment with SNMPv3 needing AES256C. Requires net-snmp support.

### PR DESCRIPTION
**Pull request by richud**
Add support for Cisco 'Privacy Password' SNMPv3 options;
CISCO-AES-192
CISCO-AES-256

### CODE REVIEW

**Comment by xmacan** [comment]
@richud I think that you forgot change file cacti.sql.

**Comment by richud** [comment]
ah yes thanks :)
added.

**Comment by TheWitness** [comment]
Can you please move this to the 1.2.x branch?

**Comment by richud** [comment]
ok done.

**Comment by TheWitness** [comment]
You moved all of develop into 1.2.x.  You should have just cherry picked your develop commit's into 1.2.x branch.  You can do this fairly easily via the GitHub Desktop.  So, one more time ;)  So, I'll close this one.  If you need some help Cherry Picking.  I might be able to upload a video, but there are already a number on YouTube.

**Pull request closed without merging**
