### PR TITLE
Ukrainian locale fix in progress

### PR DESCRIPTION
**Pull request by nightflyza**
Ukrainian locale without corrupted by automatic translation strings.

There is a chance that it will be much more acceptable for real usage, without a literal translation like Cacti as Cactuses (plants), "Aggregates" as "car spare parts" etc :)

### CODE REVIEW

**Comment by TheWitness** [comment]
Did you do this against Develop?  Are you familiar with this site: 

https://translate.cacti.net/projects/cacti/core-v1-2-x/uk/

You should not need to do a merge using a pull request, but rather use the interface.  You can change a string across all plugins too at the same time.  It's pretty convenient.  Is this I'm not sure how much rework it would be though.  Let us know.

**Comment by nightflyza** [comment]
Yep. Inititally im started translation using weblate web. 
But one day, translation was replaced with automated google translate(?) which is not acceptable and usable in most cases. This PR is try to translate project  from scratch using poedit.

**Comment by TheWitness** [comment]
That helps.  I won't merge this, but you will find it committed soon.

**Comment by TheWitness** [comment]
One thing, was this against 1.2.x or develop?

**Comment by nightflyza** [comment]
Seems it was latest core (v1.2.x) "not autotranslated" locale, backed up from weblate.

**Comment by TheWitness** [comment]
Okay, this should be merged now.  Let me know if you see the updates from translate.cacti.net.

**Comment by TheWitness** [comment]
It would be nice if you could do the same for the develop branch.  I know it's a lot of work though.

**Comment by nightflyza** [comment]
Now Ukrainian translation looks good, and not contain automatically-corrupted strings, but seems something went wrong with weblate repo sync.

Screenshot 2023-02-28 at 17-15-53 Cacti Translations


Screenshot 2023-02-28 at 17-16-19 Cacti_core (v1 2 x) — Ukrainian

Screenshot 2023-02-28 at 17-16-41 Cacti_core (v1 2 x)

**Comment by TheWitness** [comment]
Yea, our release manager @netniV locked things down, and now has to unlock it.  Once that is done, I'll unlock the repo and merge the changes.

**Pull request closed without merging**
