### PR TITLE
When importing packages, hash types are not properly processed

### PR DESCRIPTION
**Pull request by ddb4github**
* $ignorable_type_code_hashes is not initialized before used
* Incorrect arg position of array_search

### CODE REVIEW

**Review by netniV — APPROVED** [review]

**Comment by TheWitness** [comment]
This fix does not fix the package corruption.  Should get it fixed later today.

**Comment by ddb4github** [comment]
> This fix does not fix the package corruption. Should get it fixed later today.

This PR only fix `syntax error` if `$dep_status != 'met'`
For array_search func, the 2nd param must be array, current is `NULL`

```php
        var_dump($dep_hash);
        var_dump($dep_status);
        var_dump($ignorable_type_code_hashes);
        if ($dep_status == 'met') {
            $dep_status_text = "<span class='foundDependency'>" . __('Found Dependency:') . '</span>';
        } else if (array_search($ignorable_type_code_hashes, $dep_hash) === false) {
            $dep_status_text = "<span class='unmetDependency'>" . __('Unmet Dependency:') . '</span>';
            $dep_errors = true;
        }
```
```output
string(43) "hash_0101037fc923d81fd11083628731e271c3fa6a"
string(3) "met"
NULL
```

**Comment by TheWitness** [comment]
The `$needle` is what we are searching for (aka `$dep_hash`, the `$ingorable_type_code_hashes` are the `$haystack`.

```php
array_search($needle, $haystack);
```

**Comment by netniV** [comment]
@TheWitness is correct @ddb4github.  The function should have the needle first: https://www.php.net/manual/en/function.array-search.php

**Pull request merged**
