### PR TITLE
Latest QA fixes

### PR DESCRIPTION
**Pull request by netniV**

### CODE REVIEW

**Comment by cigamit** [comment]
Documentation is not permitted ;)

**Comment by netniV** [comment]
I just had a big blow up on my QA branch, I didn't realise this had been merged... 😱

**Comment by cigamit** [comment]
Well?

**Comment by netniV** [comment]
well, you shouldn't really rebase something that you've already merged 👍

**Comment by netniV** [comment]
Sorry, just realised that sounded like it completely failed, haha

**Comment by netniV** [comment]
I think the reason is that you had compressed the merge to a single commit on develop, so my branch was trying to reapply it

**Pull request merged**
