### PR TITLE
CHILAN: allow to select many data queries by period determined by p…

### PR DESCRIPTION
**Pull request by chilek**
…reviously clicked row and lately clicked row with shift key pressed

### CODE REVIEW

**Comment by cigamit** [comment]
Can you please provide an algorithmic explanation of what you are trying to accomplish with this change?

**Comment by chilek** [comment]
@cigamit:

1. Click left mouse button on given data query row mark clicked checkbox as "previously clicked" (change introduces it) and select this row (this is existing behavior).
2. Click left mouse button on given dataquery row with simultanously shift key pressed mark all data query between "previously clicked" row/checkbox and lately clicked row/checkbox as selected.

Effect: if you want to select (let's assume) 50 of 100 data query rows you make it with a few click and shift key. I hope it explains well what this change introduces.

**Comment by cigamit** [comment]
Okay, I'm good with that.  Maybe it needs to be applied to other selections as well.  Can you accomplish that in a separate pull request?

**Comment by chilek** [comment]
@cigamit: I'll to separate as much code as possible to not duplicate code. Expect the next pull request very soon ;-)

**Comment by chilek** [comment]
@cigamit: will it be ported from develop to master? I'd like to make next changes related to shift multiselections on current master and then push it to develop. Yes, I have reverse order of code flow, but this is production environment ;-)

**Comment by cigamit** [comment]
1.1.29 should be released in a week or so.  Just discussed with @ronytomen and we just have a few more issues to resolve.  It's holiday time, so we are both traveling and visiting with family though.

**Comment by chilek** [comment]
Merry Christmas, Cigamit!

**Comment by netniV** [comment]
I'll try to get some of the minor pulls sorted before the new year then ;-)

**Pull request merged**
