### PR TITLE
improve SQL query to search for nodes in tree view

### PR DESCRIPTION
**Pull request by rb83**
Removes one of the joins on the host table: by site_id. Logic behind
that join is unclear, and on first glance would return just the whole of
graph_tree_items. This behaviour may have gone unnoticed because a
default install of cacti comes without any sites defined (not even a
default one) and site_id may contain NULL. On the install where we
observed issue #4806, sites are defined however.

### CODE REVIEW

**Comment by rb83** [comment]
Closes  #4806

**Comment by netniV** [comment]
You'll need to update CHANGELOG too.

**Comment by rb83** [comment]
> You'll need to update CHANGELOG too.

Woops, keep forgetting - but in this case I guess it's because I expected some discussion.

**Comment by TheWitness** [comment]
I'm scratching my head on this whole thing.  This is completely wrong the way it was written.  I might need to close this and do it right as what I see must have been done some time way after midnight EST.

**Comment by TheWitness** [comment]
So, I'm not knocking the change proposal, but the guy who wrote it while sleep walking.  Might have been me. :)

**Comment by TheWitness** [comment]
I don't think this is my stuff.  I'll keep the Pull open but make a few light edit's before merging.

**Comment by rb83** [comment]
@TheWitness changes seem fine from our POV

**Comment by TheWitness** [comment]
Cool.

**Pull request merged**
