### PR TITLE
Change description for snmp algorithms

### PR DESCRIPTION
**Pull request by mikygee**
Hello,

I opened a feature request in order to add SHA256 and AES256 for authentication and privacy protocol.
https://github.com/Cacti/cacti/issues/3787

The problem is that in Cacti device page for snmpv3 it's written SHA and AES.

This is not accurate and it's confusing. I suppose that the person who wrote the code based the name on what snmpwalk & co wrote
```
  -a PROTOCOL           set authentication protocol (MD5|SHA|SHA-224|SHA-256|SHA-384|SHA-512)
  -x PROTOCOL           set privacy protocol (DES|AES)
```

I think it's now necessary to specify which SHA and which AES we're talking about => SHA1 and AES128

Here's the patch

```
# cat include/patch_global_arrays
--- include/global_arrays.php.orig      Thu Sep  3 00:30:45 2020
+++ include/global_arrays.php   Thu Sep  3 00:44:54 2020
@@ -582,13 +582,13 @@
 $snmp_auth_protocols = array(
        '[None]' => __('[None]'),
        'MD5'    => __('MD5'),
-       'SHA'    => __('SHA')
+       'SHA'    => __('SHA1')
 );

 $snmp_priv_protocols = array(
        '[None]' => __('[None]'),
        'DES'    => __('DES'),
-       'AES128' => __('AES')
+       'AES128' => __('AES128')
 );

 $banned_snmp_strings = array(
```

### CODE REVIEW

**Comment by mikygee** [comment]
Also please explain me (step by step) which process should I use to push code.

**Comment by TheWitness** [comment]
If you are using git desktop, switch to your branch, and the from the branches pull down, pick merge into this branch, and pick from origins 1.2.x, then once it completes, push into your repo.

**Comment by TheWitness** [comment]
Once you have caught up on commits, just push your changes to your repo and from there, there is a big button that says "create pull request".

**Comment by mikygee** [comment]
Hello TheWitness,
I'm stuck

I cloned cacti
git init
I modified the code
git add include/global_arrays.php
git commit -m "Replace SHA by SHA1 and AES by AES128"

But after i don't know what to do

**Comment by TheWitness** [comment]
MergeFromUpstream

**Comment by TheWitness** [comment]
Since you are using the cli and not the Desktop, may @netniV can help.

**Pull request merged**
