### PR TITLE
Fixed: #3769: Show whole Horizontal Scrollbar

### PR DESCRIPTION
**Pull request by ddb4github**

### CODE REVIEW

**Comment by netniV** [comment]
Not sure what that does to the overall layout by removing the table format, what does it now default to within the CSS and does that have any knock-on affect?  I'll have to checkout your branch to test against and see what differences I can see side by side.  

Also, there is no CHANGELOG entry.

**Comment by ddb4github** [comment]
Can be consider as a part of #3769, still in 1.2.15

**Comment by ddb4github** [comment]
a easy test case is: cacti 1.2.x + thold develop
   zoom in thold page: cacti/plugins/thold/thold_graph.php
   open  FireFox devtool window
   enable horizontal scrollbar or click topright rect icon in filter panel
   search ". cactiContent" FireFox->DevTool-->Inspect window
   Before fix, you can only scroll one or two column
   After fix(disable "display: table;"), you can scroll to see all columns

**Comment by TheWitness** [comment]
Tested.  Thanks!

**Pull request merged**
