### PR TITLE
#3392. Add hooks for Devices page to customize the filter and columns more f…

### PR DESCRIPTION
**Pull request by YongBoLiu**
…lexible on the page.

### CODE REVIEW

**Comment by TheWitness** [comment]
@YongBoLiu, can you please update the ChangeLog as well?

**Comment by netniV** [comment]
This should technically be against develop, as it's a feature not a bug.

**Comment by TheWitness** [comment]
I'm going with @netniV on this one.  Can you please rebase this pull request to the Develop branch?

**Comment by YongBoLiu** [comment]
ok, rebase to the Develop branch on a new PR #3406

**Pull request closed without merging**
