### PR TITLE
feature #1400: User settings should have checkbox to enable overriding of default settings

### PR DESCRIPTION
**Pull request by netniV**
This pull request introduces a tick box for enabling of user settings overrides.  This is work in progress, but I believe that most functionality has been achieved.  

The only step that should probably be added is the removal of any user settings that match default values but I'm a little unsure which defaults to refer to.  That should probably be part of the 1_2_0.php upgrade file.

Known issues:
- When disabling the setting inputs, they don't seem to become enabled again even though I'm setting disabled to false.
- Text prompts do not seem to dim despite being disabled so some CSS stlying may need to be applied on top of the disabled attribute.

### CODE REVIEW

**Comment by cigamit** [comment]
For the disabled piece, you have to evaluate the type of form element and then check for the widget attribute, and if set use the instance method 'disable' in most cases.  For text input, just add the ui-disabled class to the element.  For example, for the selectmenu:

`if ($(selector).selectmenu('instance')) {
     $(selector).selectmenu('disable')
}`

In our discussion on this topic, I stated that we should take the approach, with the user settings, of saving them on demand.  In other words, get rid of the save button, and just update as they change things.

Regardless of that, attach and animation of how this is working.  Updating things on the fly is great, but unsetting is a bit more involved.  Maybe a default button of some sort right no the page next to the settings.  I don't want the page to be gaudy though.

**Comment by cigamit** [comment]
The Console > Configuration > Settings must continue to use the Save button.  However, User Settings, I'm not to worried about as the Admin can bail our a user if the get themselves sideways.

**Comment by netniV** [comment]
Actually, now you say that, I agree with that.  I keep thing of 'settings' and thinking of all places.  But yes, on loss of focus, an ajax call to update those settings would work.  I think that will be a sepaate job from this but ti would work in conjunction with it.

**Comment by netniV** [comment]
I believe that this is ready now.  The one thing I could not figure out how to do is make the settings 'Save' button refresh the entire window if the theme option is modified, does make me wonder if we do a full refresh anyway because we've messed with settings.

**Comment by netniV** [comment]
optional settings

Here is a capture of how it works.

**Comment by cigamit** [comment]
Okay, I'm going to merge this, but as eluded to, it will change before release to remove the checks and the save button.

**Comment by cigamit** [comment]
I've now removed the 'Save' button as we discussed.  When you hover over a setting, you can 'Reset' to default.

**Pull request merged**
