### PR TITLE
Issue #1168 - Unable to copy debug information

### PR DESCRIPTION
**Pull request by netniV**
Issue #1168 is to allow debug query section to be copied to the clipboard rather than just collapsing the sections.  These mods require linkCopyDark to be added to a theme's css to prevent complete display without occuring when using linkOverDark.

The code now copies the entire table or individual sections.  By design tt expands any section copied as the DOM doesn't copy anything that is hidden.

Two issues that I'm not happy with but I'm not sure how to fix are:
- fa-plus-circle isnt really the right style to use but shows the concept.  
- button on section header is slightly too low

### CODE REVIEW

**Comment by cigamit** [comment]
Thanks to the work.  We don't use alert() though.  Use jquery dialog and present the error in a dialog.  Thanks!

**Comment by netniV** [comment]
Not sure what that means yet, as I am pretty new to using jQuery :)

I'll see if I can spot an existing usage.

**Comment by netniV** [comment]
OK, so I updated the layout.js with the spangly dialog, looks a lot nicer!  However, as you will see from the code changes, I couldn't utilise the php language functions because it's a pure JS file.  So for now I've used the English variants.  Is there a page/function/call to get a message translated already?

For example:
```
function getLanguageMessage(message) {
  // strUrl is whatever URL you need to call
  var strUrl = "<cacti>/message.php?message=" + message, strReturn = "";

  jQuery.ajax({
    url: strUrl,
    success: function(html) {
      strReturn = html;
    },
    async:false
  });

  return strReturn;
}

**Comment by cigamit** [comment]
Okay, I'll take this from here.  We have some generically translated strings in include/global_session.php that we can add to.  We did it this way so that we did not have two sources for i18n strings to be translated.  Works pretty well so far.

**Comment by cigamit** [comment]
I've made a bunch of changes including now the i18n, and some layout and fontawesome changes.

**Comment by netniV** [comment]
Cool.  I will pull them out later and check my test servers.

**Pull request merged**
