### PR TITLE
fix the issue #4435

### PR DESCRIPTION
**Pull request by kim-fitness**
Signed-off-by: kim-fitness <jianjin@cn.ibm.com>

FIx the issue for commit 3370803

### CODE REVIEW

**Comment by netniV** [comment]
Hi Kim,

Just missing a CHANGELOG emtry to cover the fix as this crosses releases.

Thanks again!

**Comment by kim-fitness** [comment]
> Hi Kim,
> 
> Just missing a CHANGELOG emtry to cover the fix as this crosses releases.
> 
> Thanks again!

Hi Mark,
I did not log an issue for the PR, would I say I'm also fixing the `issue#4435: Unable to Save Graph Settings from the Graphs pages` from the CHANGELOG, or I need to create a new issue for that?

**Comment by TheWitness** [comment]
This really should be moved to 1.2.x and section moved to a post variable.  This is due to what would appear to be a 1.2.20 on the near horizon.

**Comment by netniV** [comment]
@kim-fitness Yes, just add that to the 1.2.20 changelog.  Also, @TheWitness is correct, this is against develop not the 1.2.x branch where it ideally needs to be, but there's no harm committing to both.

**Comment by kim-fitness** [comment]
PR #4459 is created for merging into 1.2.x

**Pull request closed without merging**
