### PR TITLE
Paginator object not always translated

### PR DESCRIPTION
**Pull request by reboot1983**

### CODE REVIEW

**Comment by netniV** [comment]
I was confused by this commit, so I ended up going to your source repo to see what the change was, primarily because you have attempted to pull in the changes from the develop branch.

When creating the pull requests I've made over the past few months, I have found the best thing to do is create a fork of cacti, leaving the develop branch alone.  Then in your own repo, branch off and create an "Issue" branch that fixes the specific issue you are looking and allows you to them commit that change/create the pull request.

1. Fork cacti on github.com
2. Clone the source to your local machine
```
git clone https://github.com/<myuser>/cacti
```
3. If previously cloned, ensure you are back on your own develop branch
```
git checkout origin/develop --
```
4. If you want to create a new branch (I tend to call it Issue-<number>) using command line
```
git checkout -b Issue-1153
git push --set-upstream origin Issue-1153
```
5. If you want to create a new branch on github, do so and then checkout using
```
git checkout Issue-1153
```
6. Do your edits and use git add/git stage to mark them as ready
```
git stage <file>
```
7. Commit your changes
```
git commit
```

### Update with the latest development source
At this point, you've done everything as before.  However, you realise there have been a lot of changes to develop, and you want them.  What you now do is this:

8. If previously added an upstream, skip this
```
git remote add upstream https://github.com/cacti/cacti.git
```
9. Fetch the latest upstream sources
```
git fetch upstream
```
10. Merge the changes using
```
git merge upstream/develop
```
11. At this point, you may have conflicts due to other changes. Any file listed needs to be edited to correct the conflict between the `<<<` and `>>>` points before you then add them back in using
```
git add <file>
```
12. If all files have been resolved, then commit the changes which will default the message to 
> Merge remote-tracking branch 'upstream/develop' into Issue-1153
```
git commit
```
13. Push those latest merges up to github
```
git push
```
 
I don't know if all that is in a Wiki yet, but if not it may be worth doing so as I also got confused using the mixture of github/git when I first came to it the other month. 

What this does is allow you to keep your develop branch clean and up to date with the main source.  Additionally, when you create a pull request, it is kept clean with your changes.

### Updating main branches
if you want to update to the latest develop source on the develop branch, or master on the master branch just repeat the "Update with the latest development source" against the appropriate branches instead.  eg, update origin/develop with upstream/develop or origin/master with upstream/master.

### Creating a git patch and applying it elsewhere
Sometimes, if you have quite a lot of changes you wish to port to another branch, it's worth performing the following:

1. Get the commit hash number from github.com or from `git log`
2. Create a patch file of the difference by comparing the provided has with it's parent (^)
```
git diff -p 1c0dd0e75d8b6d234eecc63acb68280c9bae0d06^ 1c0dd0e75d8b6d234eecc63acb68280c9bae0d06 > diff.patch
```
3. This can then be applied later using
```
git apply diff.patch
```

### Example of doing this
I've used your commit as an example, which can be seen here:
> https://github.com/netniV/cacti/commits/Issue-1153

You will see that I committed your change, then I pulled in all the latest development changes (mostly from today as I was fairly up to date).

**Comment by reboot1983** [comment]
Wow! What happened here then? Sorry about this!

What I did yesterday was updating my fork (git fetch upstream) and merge it into my develop brach (git merge upstream/develop), then today I noticed some translations not applied correctly. So i fixed it, committed it and pushed it. But, i've forgotten to fetch and merge first. So after that I created a PR. And I guess it ended up in this.. Which wasn't my intention..

Guess we'd better ignore this PR then?

**Comment by reboot1983** [comment]
Fixed it in #1154

**Comment by cigamit** [comment]
I went ahead and committed this separately.  Thanks for pointing this out.  Thought they were already done.

**Pull request closed without merging**
