### PR TITLE
Fix timespan calculation

### PR DESCRIPTION
**Pull request by arjanoosting**
The cacti_graph.php displayed the wrong graph when select the 30min, 2hour or daily average.

This was caused by the timespan calculated by rrd.php which was incorrect.
The code used the rra_id as the data_source_profile.id which should be the data_source_profiles_rra.id.

This patch finds the correct inner join  of data_source_profile and data_source_profiles_rra used the local_graph_id and rra_id

### CODE REVIEW

**Comment by cigamit** [comment]
arjanoosting you don't need the extra joins, just change the initial where to pick the correct id.  Data Source Profiles are not duplicated for each graph like other Cacti items are.  Therefore, you really only need the RRAid to match.  Can you redo this to simply change the where clause and remove the extra joins?

**Comment by arjanoosting** [comment]
Removed unnecessary joins

**Comment by cigamit** [comment]
Did you close intentionally?  Or were you going to open a second?

**Comment by cigamit** [comment]
No need to reply.  Thanks for testing!

**Pull request closed without merging**
