### PR TITLE
REQ: SCRIPT FOR AUTOUPDATE

### PR DESCRIPTION
**Pull request by xssec**
Hi,

Firstable thank you for the great job. It would be cool if there is tools or feature for autoupdate cacti 😄

### CODE REVIEW

**Comment by pautiina** [comment]
Already fixed on commit b7d9b4c9b1c42eae3043f396a4cf342d1572def3. You can close the pool request

**Comment by netniV** [comment]
Note sure you commented on the correct issue here paultina.

**Comment by cigamit** [comment]
This has been resolved already in this commit: https://github.com/Cacti/cacti/commit/b7d9b4c9b1c42eae3043f396a4cf342d1572def3.

**Comment by netniV** [comment]
OK, I see why I was confused, the opening comment here is actually nothing to do with the commit.

**Pull request closed without merging**
