### PR TITLE
Changed CLOG to use regex replacement for Device[] and DS[]

### PR DESCRIPTION
**Pull request by netniV**
Also fixes issue #1158

### CODE REVIEW

**Comment by cigamit** [comment]
There are definitely issues here.

Here is the RAW log output from spine.

clograw

Here is the output before the changes:

clogorig

Here is the output after your changes.  A few things to note: 1) Graphs missing, 2) DS hyperlinks missing.

clognew

**Comment by netniV** [comment]
That will be because SPINE Isn't following the standard of the PHP side.  On the PHP side there are no spaces around the device.  I can update the regex to cope with that though.

**Comment by netniV** [comment]
I've made a local update to correct the spine issue, can you give me text versions of those logs so i can insert them into my test system

**Comment by cigamit** [comment]
Looks like a syntax error from travis' perspective.

**Comment by netniV** [comment]
Yeah I committed the changes as I was moving between work and home, but I was hoping for those logs first before I actually tested it in anger :)

**Pull request merged**
