### PR TITLE
Fix missing include

### PR DESCRIPTION
**Pull request by rlaager**
With Cacti on Ubuntu 20.04:

```
$ sudo php /usr/share/cacti/cli/add_datasource.php --host-id=261 --data-template-id=90
PHP Fatal error:  Uncaught Error: Call to undefined function api_data_source_cache_crc_update() in /usr/share/cacti/site/lib/utility.php:745
Stack trace:
#0 /usr/share/cacti/cli/add_datasource.php(99): push_out_host()
#1 {main}
  thrown in /usr/share/cacti/site/lib/utility.php on line 745
```

This PR fixes that.

### CODE REVIEW

**Comment by TheWitness** [comment]
Could you rebase this on the 1.2.x branch.  Please update the CHANGELOG as well.  Thanks.

**Comment by netniV** [comment]
Wasn't this routine in a library that was not included, then included, then removed again ? Cryptic I know ;-)

Can't recall what that issue was without searching but just don't want to fall into a repeat performance if its happening again?

**Comment by rlaager** [comment]
Updated as requested.

**Comment by TheWitness** [comment]
This is still targted improperly to the develop branch.  We need it pointed to the 1.2.x branch.  I'm going to close, just fork the 1.2.x branch and re-open in that branch.  I'll do the same with the other.

**Comment by TheWitness** [comment]
If you are using the GitHub desktop, you simply need to fork whatever version, which you have already done, then switch the branch to 1.2.x and carry your changes forward to that branch, and open a new pull request.

**Comment by rlaager** [comment]
Yeah, I'm also not sure how to change the target of the pull request. The commit itself was correctly rebased on 1.2.x. I just opened a new PR for the correct target branch as you suggested.

**Comment by TheWitness** [comment]
Thanks for your contribution.

**Pull request closed without merging**
