### PR TITLE
Hotfix/htaccess apache2.4

### PR DESCRIPTION
**Pull request by emeidi**
Make .htaccess files compatible with both Apache 2.4 and 2.2 at the same time

### CODE REVIEW

**Comment by smiles1969** [comment]
Looks like you are getting that .travis.yml extra line as well. It was messing up my pull requests.

What is causing that?

**Comment by ronytomen** [comment]
Not sure what is going on,  but based on the commits I see in this pull request it appears to be been forked from master.

**Comment by ronytomen** [comment]
I will have to manually merge this into develop.

**Comment by ronytomen** [comment]
@emeidi You might want to consider deleting your fork and re-forking from the develop branch.

From the commits in this pull request, it looks like you merge master into develop.  Also I see evidence of earlier changes to the master branch in the commit history of this pull request.

**Comment by ronytomen** [comment]
Manually merge into `develop` branch at commit 77ea5599279aec84e5688842b28c8e27d6c5fbfe.

**Pull request closed without merging**
