### PR TITLE
Add Gradient support for Area charts

### PR DESCRIPTION
**Pull request by thurban**
Add some gradient support to have the charts look a bit nicer.

Maybe a config setting to switch between the old and gradient support would be nice ... ?

### CODE REVIEW

**Comment by thurban** [comment]
Liecenses for the additional functions is GPLv2. 

**colourBrightness function :**
// from: http://lab.clearpixel.com.au/2008/06/darken-or-lighten-colours-dynamically-using-php/  License: unknown
// The code is based on the CSSColor project of the same person from here: http://www.barelyfitz.com/projects/csscolor/ License: GPLv2

**Gradient function license is GPLv2 as well:**
// from https://github.com/lingej/pnp4nagios/blob/master/share/pnp/application/helpers/rrd.php

**Comment by thurban** [comment]
going to re-design and place into correct branch once done

**Comment by browniebraun** [comment]
@thurban 
Hi Tomas, was there any version issue or anything else why you have closed this PR?

Regards
-Andi

**Comment by TheWitness** [comment]
Found it.  Some of these changes are obsolete now.  But I think could edit the pull request and merge it after making those changes.

**Comment by TheWitness** [comment]
Well we can not re-open as Thomas deleted his feature branch, but we can still savage this.

**Comment by netniV** [comment]
Just for those who stumble on this, it has been merged via a new PR now.

**Pull request closed without merging**
