### PR TITLE
SQL_CALC_FOUND_ROWS instead of two queries

### PR DESCRIPTION
**Pull request by reboot1983**
In reference of issue #473

### CODE REVIEW

**Comment by cigamit** [comment]
Before I merge this, can you rationalize the following article from Percona.  Seems like it's not always a better solution.  https://www.percona.com/blog/2007/08/28/to-sql_calc_found_rows-or-not-to-sql_calc_found_rows/  The article is a few years old, but I expect that not much has changed.

**Comment by reboot1983** [comment]
Good point. On my environment I've tested it runs ok, but... I see the same behaviour as explained at the Percona blog site. This might be explained by the combination of the refactored queries, and it looks like the code is not always using a limit (which makes the query identical in execution).

Of course, there are more complex cacti environments (with more trees, more users, (more) authorization groups, etc.) where these specific scenario's might be slower. I'm unable to test this.

I guess you might want to consider rejecting this one.

**Comment by cigamit** [comment]
How about this.  Let's mark this to ask for help and see if we can get a volunteer who knows enough about this and has a large enough environment to do a real good test.  I'll keep it open for the moment.

**Comment by cigamit** [comment]
I'm going to close this.  InnoDB tables have no such optimizations for this.  It's a feature GAP in MySQL/MariaDB as documented by many users.  Let's hope that these two suppliers of Databases can refocus on providing butter support under InnoDB moving forward.  At that time, we can re-open/re-visit this.

**Pull request closed without merging**
