### PR TITLE
Import and Export cacti.sql in order to clean up SQL formating issues.

### PR DESCRIPTION
**Pull request by dsclassen**
Perhaps these types of formatting changes aren't appropriate, but I thought I'd "sanitize" the cacti.sql by importing into mysql and exporting it back out.

1. This resulted in the CREATE tables statements being reordered alphabetically.
2. Table indexes are now all at the very bottom of the sql file.
3. All table and column names and now enclosed in backquotes (Protects column and table names formed with special characters or keywords). This may also allow easier comparison of cacti.sql file changes in the future.

### CODE REVIEW

**Comment by cigamit** [comment]
Okay, a few things before this is merged:

1) Resolve conflicts
2) Make sure that are no charsets included.
3) Make a Wiki article on the GitHub site including mysqldump instructions on preparing this file for new pull requests in the future.

That Wiki should be a generalized how to help.  You can start it with these instructions, adding the install directory changes as well.

Once you have done that, I think it would be good to merge.  However, others in the team will need to comment.

There are some downsides, as I normally just run a 'show create table' and compare that visually against what is in the cacti.sql.  So, this makes me have to goto at least two places to find those things.  It's not a show stopper, just my thoughts.

**Comment by ronytomen** [comment]
Also, when exporting from mysql use the compatibility flags to make sure the export is compatible with the minimum version we support.

**Comment by dsclassen** [comment]
Thanks for the input. I actually dumped this using phpMyAdmin, which now that I think about it is suboptimal for this PR because it would require another relatively complicated dependency. Therefore, I will redo this using a pure command-line mysqldump method.

There is a --compatible flag for mysqldump, but I'm unsure what value should be specified. What is the lowest MySQL version supported by cacti? Options for mysqldump include: ansi, mysql323, mysql40, postgresql, oracle, mssql, db2, maxdb, no_key_options, no_table_options, or no_field_options. 

I will use the --skip-set-charset option to prevent charsets from being included.

Do I add a wiki page on my fork? will that be part of the pull request?

**Comment by dsclassen** [comment]
There are still `DEFAULT CHARSET=latin1` statements in the `ENGINE` specification for each table. Is this a problem? Also the last commit does not contain the `--compatible` flag so I will need to figure out what keyword to include.

**Comment by dsclassen** [comment]
I think I'm getting closer. Not sure why Travis failed.

**Comment by cigamit** [comment]
Here is the Wiki link:

https://github.com/Cacti/cacti/wiki

I'm thinking you start a 'How to Contribute' including topics like:

1) Creating a Pull Request
2) Updating database columns
a) cacti.sql
b) 1_x_x_to_1_x_(x+1).php
c) ?
3) Coding Standards
a) braketing
b) hard tabs
c) prepared statements
d) variable naming
e) documentation

Something like that.

The reason for the Travis failure is that TYPE = InnoDB was removed from MySQL 5.5+.  Make sure you do MySQL 5.5+ as the compatibility level.  Then it will be ENGINE = InnoDB.

**Comment by dsclassen** [comment]
I'd be happy to add a Contribution guide to the wiki, but I don't have permission, and it's not clear to me exactly how to clone/fork it.

**Comment by cigamit** [comment]
I just chatted with Tony.  Give us a day or two to figure things out.

**Comment by dsclassen** [comment]
I'm in no hurry, and if your decide this is too much trouble for your existing workflow I would totally understand. It was just my OCD nature to want to clean up the initial sql file. Ultimately one could then mysqldump a fully upgraded cacti.sql (without the data - just the schema) and do a relatively easy diff to see if any table updates/alterations have been missed or gone awry.

**Comment by cigamit** [comment]
Tony agreed to verify if he can give you Wiki access.  Might take him a day or two.

**Comment by cigamit** [comment]
Scott, I don't see anything to merge at the moment.  I'm going to close this.  Tony should get your Wiki access done hopefully this weekend.  We will be doing the 1.1.6 release on Sunday.  So, we'll wait on the next release for this anyway.  Thanks for you and others keeping us honest thought.  That graph creation bug gave me a scare.  That is one dog we don't want to let out of the cage.  We have not had this rate of change in a decade.  So, we all appreciate you and a few others staying in the deep end.

**Pull request closed without merging**
