### PR TITLE
feature: Links and names for Poller, Data Query and Data Sources

### PR DESCRIPTION
**Pull request by netniV**
I have updated the CLOG functionality so that links/names for Poller, Data Query and Data Sources now show in clog display to make it easier to understand what sources are associated with the log entry.

### CODE REVIEW

**Comment by netniV** [comment]
I have a slight update to this to make it easier to add more dynamic options.  It will be ready hopefully tomorrow.

**Comment by netniV** [comment]
screen shot 2018-02-03 at 12 28 58
screen shot 2018-02-03 at 12 29 20

**Comment by cigamit** [comment]
This is pretty impressive.  Just made a few style changes.

**Comment by netniV** [comment]
Yeah I saw them, I was rushing out the door this morning so didn't do a final style check just wanted it available 👍 

Thanks for the 'impressive' comment.  I wasn't happy with keep adding variables and duplicating the preg as I thought that could end up getting slower.  I'm also wondering about potentially caching the results since we are doing each SQL call on every line that is read.  Really, if we've done the lookup once, we should not need to do it again but refer to the cache'd array.

**Comment by netniV** [comment]
I just spotted a change that didn't make it into the commit.
```diff
--- a/lib/clog_webapi.php
+++ b/lib/clog_webapi.php
@@ -555,7 +555,7 @@ function clog_get_regex_array() {
                        4 => array('name' => 'Poller', 'regex' => '( Poller\[)([, \d]+)(\])',  'func' => 'clog_regex_poller'),
                        5 => array('name' => 'RRA',    'regex' => "([_\/])(\d+)(\.rrd&#039;)", 'func' => 'clog_regex_rra')
                );
-               $regex_array = api_plugin_hook_function('clog_regex_array',$regex_array);
+               //$regex_array = api_plugin_hook_function('clog_regex_array',$regex_array);
                $regex_complete = '';
                foreach ($regex_array as $regex_key => $regex_setting) {
                        $regex_complete .= (strlen($regex_complete)?')|(':'').$regex_setting['regex'];
```
I was going to add functionality for plugins but I think that should be in the next phase.

**Comment by cigamit** [comment]
I don't think it hurts anything at this point unless you want to change the hook name.

**Comment by netniV** [comment]
Haven’t really decided how it would be implemented at this point. Probably best just in case it changes so nothing relies on it if that update is a few down the line.

**Pull request merged**
