### PR TITLE
Fixed: two minor issue about function  api_plugin_db_table_create

### PR DESCRIPTION
**Pull request by ddb4github**
* Fixed: Function api_plugin_db_table_create should apply charset during creating to avoid index length issue. 
* Fixed: innodb_file_format is case insensitive now

### CODE REVIEW

**Review by netniV — COMMENTED** [review]
I am sure there was a reason to have the charset done separately as an alter. Was there a reason for moving that up?

**Comment by TheWitness** [comment]
Will this not work beyond MariaDB 10.6 where the innodb_file_format was deprecated are reports an empty string?  Let's be careful.  We want a dynamic row format for sure where we can though.

**Comment by TheWitness** [comment]
I'll have some time to test this on 10.9 on Sunday.

**Comment by ddb4github** [comment]
> Will this not work beyond MariaDB 10.6 where the innodb_file_format was deprecated and reports an empty string? Let's be careful. We want a dynamic row format for sure where we can though.

In MariaDB 5.5, innodb_file_format is always 'Barracuda' whatever lowercase/uppercase。
In MariaDB 10.5, innodb_file_format will be shown as configured value, like `Barracuda` or `barracuda`

By MariaDB doc, innodb_file_format will be removed, and row_format default `dynamic`.
So ignore `row_format` is acceptable if checking innodb_file_format failure

**Comment by netniV** [comment]
Still not sure about the CHARSET movement ?

**Comment by ddb4github** [comment]
> Still not sure about the CHARSET movement ?

Moved by @TheWitness for #3985, need more confirmation from @TheWitness

**Comment by netniV** [comment]
I knew there was a reason we moved it.  You PR seems to be undoing that issue with CHARSET.

**Comment by ddb4github** [comment]
Append more fixing for 
image

**Review by netniV — APPROVED** [review]

**Comment by ddb4github** [comment]
For previous screenshot issue,  we should also  take some line-changed in lib/utility.php.
But I'm not sure add a new `measure` like 'equalicase`, or directly ignore case in current `equal measure`

**Comment by netniV** [comment]
We can just `ucfirst` if it's the innodb format and we are above a certain version?  Would that work?  Feel free to create a separate issue for that.

**Comment by TheWitness** [comment]
@ddb4github @netniV, who will handle the 1.3.x / develop merge?  `strtolower` was the right call.  Again, the innodb_file_format is deprecated and removed in future releases.  Something maybe we just worry about in `develop`.

**Comment by ddb4github** [comment]
> @ddb4github @netniV, who will handle the 1.3.x / develop merge? `strtolower` was the right call. Again, the innodb_file_format is deprecated and removed in future releases. Something maybe we just worry about in `develop`.

Create a new PR for develop?

**Comment by netniV** [comment]
That would be the correct call. You should just be able to cherry pick this commit on to the branch.

**Pull request merged**
