### PR TITLE
Allow graph right_axis scale to be negative.

### PR DESCRIPTION
**Pull request by F-i-f**
Negative scales are supported by rrdtool.
Also improve the regular expression used for matching numbers.

### CODE REVIEW

**Comment by TheWitness** [comment]
Cn you pleas update the CHANGELOG too?

**Comment by F-i-f** [comment]
Done, also created bug #3457 for reference.

**Comment by TheWitness** [comment]
@F-i-f, wondering if you can rebase this on the 1.2.x branch as it is a bug?

**Comment by TheWitness** [comment]
Sorry about the extra work.

**Comment by F-i-f** [comment]
Sure.
Closing this PR, as it's been superseded by PR #3465.

**Pull request closed without merging**
