### PR TITLE
Fix issue #1189 and #1191

### PR DESCRIPTION
**Pull request by netniV**
Combined fix for issues #1189 and 1191:

-issue#1189: Allow ability to sort tree list by name asc/desc
-issue#1191: Tree sequences were not set or checked

### CODE REVIEW

**Comment by cigamit** [comment]
This is a bit of a hack.  The idea of selecting things is to work on just those things, but what you are doing is sorting the tree, which would better be handled by a button.  It does not belong in the Dropdown Actions.

**Comment by cigamit** [comment]
Also, when you sort by the 'order' column, you will see the move up/down links.

**Comment by netniV** [comment]
Yes, I found the up/down buttons but they only apply to the individual items, not the whole list.  If it was to be a button, how would you prefer it be presented?

**Comment by cigamit** [comment]
I have essentially merged this in the last commit.  So, I am going to close this one.  It was going to be easier.  Thanks for the motivation.  Keep up the great work!

**Comment by netniV** [comment]
No worries, it looks code from a coding perspective.  It does also mean I could reduce the QuickTree to using the buttons rather than drop down actions (though I think I will leave that for now).

**Pull request closed without merging**
